/************************************************************************
*                                                                       *
*       Adding an X-Window interface to SMART --- smart_xsec_ui.h       *
*                                                                       *
*                                                                       *
*    by: Victuria Chiu, senior in CS from Univ. of Cal. at Berkeley,    *
*                e-mail: victoria@csr.lbl.gov                           *
*                                                                       *
*        Tong Li, graduate student in CS from Oregon State University,  *
*                e-mail: lit@mist.cs.orst.edu                           *
*                                                                       *
*    at Lawrence berkeley Laboratory, Summer 1991                       *
*                                                                       *
************************************************************************/

/*
 * smart_xsec_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `smart_xsec.G'.
 * THIS FILE HAS BEEN ALTERED BY HAND. Therefore gxv is disabled to avoid
 * overwriting this file.
 */
#ifndef	smart_xsec_HEADER
#define	smart_xsec_HEADER

/*
 * smart_xsec_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `smart_xsec.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	document_popup;
	Xv_opaque	doc_popup_control;
	Xv_opaque	docnext_button;
	Xv_opaque	docdone_button;
	Xv_opaque	doc_textpane;
} smart_xsec_document_popup_objects;

extern smart_xsec_document_popup_objects	*smart_xsec_document_popup_objects_initialize();

extern Xv_opaque	smart_xsec_document_popup_document_popup_create();
extern Xv_opaque	smart_xsec_document_popup_doc_popup_control_create();
extern Xv_opaque	smart_xsec_document_popup_docnext_button_create();
extern Xv_opaque	smart_xsec_document_popup_docdone_button_create();
extern Xv_opaque	smart_xsec_document_popup_doc_textpane_create();

typedef struct {
	Xv_opaque	help_popup;
	Xv_opaque	help_popup_conrol;
	Xv_opaque	helppopup_msg;
	Xv_opaque	helpdone_button;
	Xv_opaque	help_textpane;
} smart_xsec_help_popup_objects;

extern smart_xsec_help_popup_objects	*smart_xsec_help_popup_objects_initialize();

extern Xv_opaque	smart_xsec_help_popup_help_popup_create();
extern Xv_opaque	smart_xsec_help_popup_help_popup_conrol_create();
extern Xv_opaque	smart_xsec_help_popup_helppopup_msg_create();
extern Xv_opaque	smart_xsec_help_popup_helpdone_button_create();
extern Xv_opaque	smart_xsec_help_popup_help_textpane_create();

typedef struct {
	Xv_opaque	savelast_popup;
	Xv_opaque	savelast_popup_control;
	Xv_opaque	savelast_filetext;
	Xv_opaque	savelast_ok_button;
} smart_xsec_savelast_popup_objects;

extern smart_xsec_savelast_popup_objects	*smart_xsec_savelast_popup_objects_initialize();

extern Xv_opaque	smart_xsec_savelast_popup_savelast_popup_create();
extern Xv_opaque	smart_xsec_savelast_popup_savelast_popup_control_create();
extern Xv_opaque	smart_xsec_savelast_popup_savelast_filetext_create();
extern Xv_opaque	smart_xsec_savelast_popup_savelast_ok_button_create();

typedef struct {
	Xv_opaque	advance_popup;
	Xv_opaque	adv_popup_control;
	Xv_opaque	advdone_button;
	Xv_opaque	doc_textpane1;
} smart_xsec_advance_popup_objects;

extern smart_xsec_advance_popup_objects	*smart_xsec_advance_popup_objects_initialize();

extern Xv_opaque	smart_xsec_advance_popup_advance_popup_create();
extern Xv_opaque	smart_xsec_advance_popup_adv_popup_control_create();
extern Xv_opaque	smart_xsec_advance_popup_advdone_button_create();
extern Xv_opaque	smart_xsec_advance_popup_doc_textpane1_create();
#endif
