/************************************************************************
*                                                                       *
*       Adding an X-Window interface to SMART --- smart_xmain_ui.h      *
*                                                                       *
*                                                                       *
*    by: Victuria Chiu, senior in CS from Univ. of Cal. at Berkeley,    *
*                e-mail: victoria@csr.lbl.gov                           *
*                                                                       *
*        Tong Li, graduate student in CS from Oregon State University,  *
*                e-mail: lit@mist.cs.orst.edu                           *
*                                                                       *
*    at Lawrence berkeley Laboratory, Summer 1991                       *
*                                                                       *
************************************************************************/
/*
 * smart_xmain_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `smart_xsec.G'.
 * THIS FILE HAS BEEN ALTERED BY HAND. Therefore gxv is disabled to avoid
 * overwriting this file.
 */

#ifndef	smart_xmain_HEADER
#define	smart_xmain_HEADER

/*
 * smart_xmain_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `smart_xmain.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;

extern Xv_opaque	smart_xmain_quit_menu_create();
extern Xv_opaque	smart_xmain_advanced_menu_create();

typedef struct {
	Xv_opaque	basewindow;
	Xv_opaque	main_control;
	Xv_opaque	retrieve;
	Xv_opaque	more;
	Xv_opaque	keywords;
	Xv_opaque	advanced;
	Xv_opaque	quit;
	Xv_opaque	feedback;
	Xv_opaque	next;
	Xv_opaque	clear;
	Xv_opaque	help;
	Xv_opaque	save;
	Xv_opaque	general_msg;
	Xv_opaque	user_textpane;
	Xv_opaque	main_control2;
	Xv_opaque	title_list;
} smart_xmain_basewindow_objects;

extern smart_xmain_basewindow_objects	*smart_xmain_basewindow_objects_initialize();

extern Xv_opaque	smart_xmain_basewindow_basewindow_create();
extern Xv_opaque	smart_xmain_basewindow_main_control_create();
extern Xv_opaque	smart_xmain_basewindow_retrieve_create();
extern Xv_opaque	smart_xmain_basewindow_more_create();
extern Xv_opaque	smart_xmain_basewindow_keywords_create();
extern Xv_opaque	smart_xmain_basewindow_advanced_create();
extern Xv_opaque	smart_xmain_basewindow_quit_create();
extern Xv_opaque	smart_xmain_basewindow_feedback_create();
extern Xv_opaque	smart_xmain_basewindow_next_create();
extern Xv_opaque	smart_xmain_basewindow_clear_create();
extern Xv_opaque	smart_xmain_basewindow_help_create();
extern Xv_opaque	smart_xmain_basewindow_save_create();
extern Xv_opaque	smart_xmain_basewindow_general_msg_create();
extern Xv_opaque	smart_xmain_basewindow_user_textpane_create();
extern Xv_opaque	smart_xmain_basewindow_main_control2_create();
extern Xv_opaque	smart_xmain_basewindow_title_list_create();
#endif
