#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1998
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  This Makefile has settings that apply to everything compiled
#  on the SPARC/SunOS architecture.

############################################################

#  $Id$

#  $Log$
#  Revision 1.2  1998/05/28 15:03:16  wenger
#  More fixes for new Tcl/Tk installation.
#
#  Revision 1.1  1998/03/04 18:41:45  wenger
#  Added <arch>/Makefile.config files that now hold stuff like the
#  PERL_CORE definitions so those don't have to be repeated in all
#  of the lower level makefiles; various other compile fixes; changed
#  version to 1.5.2.
#

############################################################

PERL_CORE = /s/perl/lib/CORE

ARCH_FLAGS = -DSUN -I/s/X11/include -I/s/tcl7.4/include

GLINCLUDE = -I/s/mesa-2.4/include

ARCH_ENDIAN = -DBYTE_BIG_ENDIAN -DWORD_BIG_ENDIAN -D_BIG_ENDIAN

ARCH_COLLECTOR  = \
	/s/gcc-2.7.1/sun4m_412/lib/gcc-lib/sparc-sun-sunos4.1.3/2.7.1/ld
