ARCH_FLAGS   = -DSUN -I/usr/sup/tcl/include
ARCH_LDFLAGS = -L/usr/sup/tcl/lib
ARCH_LDPOST  =

VPATH = ../../ams
include $(VPATH)/Makefile.base

depend:
	makedepend -I../../graphics -I../../graphics.new \
		-I../../tape -I/usr/sup/tcl/include $(VPATH)/*.c

# DO NOT DELETE THIS LINE -- make depend depends on it.

MapClassInfo.o: /usr/include/sys/time.h /usr/include/sys/time.h
MapClassInfo.o: /usr/include/math.h /usr/include/floatingpoint.h
MapClassInfo.o: /usr/include/sys/ieeefp.h /usr/sup/tcl/include/tcl.h
MapClassInfo.o: /usr/include/stdio.h ../../graphics/DeviseTypes.h
MapClassInfo.o: ../../graphics/Display.h ../../graphics/Geom.h
MapClassInfo.o: ../../graphics/Dispatcher.h ../../graphics/DList.h
MapClassInfo.o: ../../graphics/Exit.h ../../graphics/VisualArg.h
MapClassInfo.o: ../../graphics/Color.h ../../graphics/Journal.h
MapClassInfo.o: ../../graphics/ColorMgr.h ../../graphics.new/RectShape.h
MapClassInfo.o: ../../graphics/Transform.h ../../graphics/WindowRep.h
MapClassInfo.o: ../../graphics/Pattern.h ../../graphics/DevisePixmap.h
MapClassInfo.o: ../../graphics/Compress.h ../../graphics.new/Shape.h
MapClassInfo.o: ../../graphics/Control.h ../../graphics.new/TDataCMap.h
MapClassInfo.o: ../../graphics.new/ConnectorShape.h
MapClassInfo.o: ../../graphics.new/Connector.h ../../graphics.new/ShapeID.h
MapClassInfo.o: ../../graphics.new/GDataBin.h ../../graphics.new/RecId.h
MapClassInfo.o: ../../graphics.new/ActionDefault.h ../../graphics/Action.h
MapClassInfo.o: ../../graphics/Util.h /usr/include/assert.h
MapClassInfo.o: /usr/include/stdlib.h /usr/include/sys/stdtypes.h
MapClassInfo.o: /usr/include/strings.h /usr/include/ctype.h
MapClassInfo.o: ../../graphics/Selection.h ../../graphics/View.h
MapClassInfo.o: ../../graphics/ViewWin.h ../../graphics/ViewCallback.h
MapClassInfo.o: ../../graphics/AttrList.h ../../graphics/Config.h
MapClassInfo.o: ../../graphics/Cursor.h ../../graphics/Init.h
MapClassInfo.o: ../../graphics/BufPolicy.h
MapClassInfo.o: ../../graphics.new/TDataMapDispatch.h
MapClassInfo.o: ../../graphics.new/TDataMap.h ../../graphics.new/Bitmap.h
MapClassInfo.o: ../../graphics.new/GDataRec.h
MapClassInfo.o: ../../graphics.new/DispQueryProc.h
MapClassInfo.o: ../../graphics.new/QueryProcSimple.h
MapClassInfo.o: ../../graphics.new/QueryProc.h ../../graphics.new/BufHint.h
MapClassInfo.o: ../../graphics.new/QueryProcFull.h
MapClassInfo.o: ../../graphics.new/QPRange.h ../../graphics.new/BufMgr.h
MapClassInfo.o: ../../graphics.new/BufferPolicy.h
MapClassInfo.o: ../../graphics.new/RecOrder.h ../../graphics.new/Temp.h
MapClassInfo.o: ../../graphics/ViewWinVer.h ../../graphics.new/Snapshot.h
MapClassInfo.o: ../../graphics.new/ViewScatter.h
MapClassInfo.o: ../../graphics.new/ViewGraph.h ../../ams/MapClassInfo.h
MapClassInfo.o: ../../graphics/ClassDir.h ../../ams/Soil.h ../../ams/AmsMap.h
ams.o: /usr/include/sys/types.h /usr/include/sys/stdtypes.h
ams.o: /usr/include/sys/sysmacros.h /usr/include/sys/time.h
ams.o: /usr/include/sys/time.h /usr/include/stdio.h
ams.o: ../../graphics/DeviseTypes.h ../../graphics/Dispatcher.h
ams.o: ../../graphics/DList.h ../../graphics/Exit.h
ams.o: ../../graphics/VisualArg.h ../../graphics/Color.h
ams.o: ../../graphics/Journal.h ../../graphics/Display.h
ams.o: ../../graphics/Geom.h /usr/include/math.h /usr/include/floatingpoint.h
ams.o: /usr/include/sys/ieeefp.h ../../graphics/ColorMgr.h
ams.o: ../../graphics/Control.h ../../graphics/Init.h
ams.o: ../../graphics/BufPolicy.h ../../graphics/WinClassInfo.h
ams.o: ../../graphics/ClassDir.h ../../graphics.new/MapInterpClassInfo.h
ams.o: ../../graphics/VisualLinkClassInfo.h ../../graphics/View.h
ams.o: ../../graphics/ViewWin.h ../../graphics/WindowRep.h
ams.o: ../../graphics/Transform.h ../../graphics/Pattern.h
ams.o: ../../graphics/DevisePixmap.h ../../graphics/Compress.h
ams.o: ../../graphics/ViewCallback.h ../../graphics/AttrList.h
ams.o: ../../graphics/Config.h ../../graphics/Cursor.h
ams.o: ../../graphics/AxisLabelClassInfo.h ../../graphics.new/ViewClassInfo.h
ams.o: ../../graphics.new/CompositeParser.h ../../graphics.new/RecInterp.h
ams.o: ../../graphics.new/QueryProc.h ../../graphics.new/RecId.h
ams.o: ../../tape/QueryProcTape.h ../../graphics.new/QPRange.h
ams.o: ../../tape/SortedTable.h /usr/include/assert.h
ams.o: ../../graphics.new/GData.h ../../graphics.new/TData.h
ams.o: ../../graphics.new/RecOrder.h ../../graphics.new/BufMgr.h
ams.o: ../../graphics.new/BufHint.h ../../graphics.new/BufferPolicy.h
ams.o: ../../graphics.new/ViewGraph.h ../../graphics.new/TDataMap.h
ams.o: ../../graphics.new/ShapeID.h ../../graphics.new/Bitmap.h
ams.o: ../../graphics.new/GDataRec.h ../../graphics/CursorClassInfo.h
ams.o: ../../tape/TDataTapeInterp.h ../../tape/TDataTape.h
ams.o: ../../tape/tapedrive.h ../../tape/machdep.h /usr/include/limits.h
ams.o: /usr/include/sys/param.h /usr/include/machine/param.h
ams.o: /usr/include/machine/devaddr.h /usr/include/sys/signal.h
ams.o: /usr/include/vm/faultcode.h /usr/include/sys/ioctl.h
ams.o: /usr/include/sys/ttychars.h /usr/include/sys/ttydev.h
ams.o: /usr/include/sys/ttold.h /usr/include/sys/ioccom.h
ams.o: /usr/include/sys/ttycom.h /usr/include/sys/filio.h
ams.o: /usr/include/sys/sockio.h /usr/include/sys/wait.h
ams.o: /usr/include/sys/ipc.h /usr/include/sys/shm.h
ams.o: /usr/include/machine/mmu.h /usr/include/sys/sem.h
ams.o: ../../graphics/ParseCat.h ../../graphics.new/Command.h
ams.o: ../../graphics/Timer.h ../../ams/MapClassInfo.h
amsStat.o: /usr/include/stdio.h /usr/include/sys/types.h
amsStat.o: /usr/include/sys/stdtypes.h /usr/include/sys/sysmacros.h
amsStat.o: /usr/include/sys/stat.h /usr/include/fcntl.h
amsStat.o: /usr/include/sys/fcntlcom.h /usr/include/limits.h
amsStat.o: /usr/include/sys/uio.h /usr/include/unistd.h
amsStat.o: ../../graphics.new/TDataAppend.h ../../graphics.new/TData.h
amsStat.o: ../../graphics/DeviseTypes.h ../../graphics.new/RecId.h
amsStat.o: ../../graphics.new/RecOrder.h ../../graphics/VisualArg.h
amsStat.o: ../../graphics/Color.h ../../graphics/DList.h
amsStat.o: ../../graphics/Exit.h ../../graphics.new/DiskFile.h
amsStat.o: ../../graphics.new/ams.h /usr/include/math.h
amsStat.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
extendAms.o: /usr/include/stdio.h /usr/include/sys/types.h
extendAms.o: /usr/include/sys/stdtypes.h /usr/include/sys/sysmacros.h
extendAms.o: /usr/include/sys/stat.h /usr/include/fcntl.h
extendAms.o: /usr/include/sys/fcntlcom.h /usr/include/limits.h
extendAms.o: /usr/include/sys/uio.h /usr/include/unistd.h
extendAms.o: ../../graphics.new/ams.h /usr/include/math.h
extendAms.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
testdir.o: /usr/include/stdio.h /usr/include/sys/types.h
testdir.o: /usr/include/sys/stdtypes.h /usr/include/sys/sysmacros.h
testdir.o: /usr/include/sys/dir.h
