ARCH_FLAGS = -DSUN -I/usr/sup/tcl/include
ARCH_LDFLAGS = -L/usr/sup/tcl/lib
#CC = CC
VPATH = /p/miron/miron/DEVise/src/ams
include /p/miron/miron/DEVise/src/ams/Makefile.sun
#DO NOT DELETE THIS LINE -- make depend depends on it.
