/*
  ========================================================================
  DEVise Data Visualization Software
  (c) Copyright 1992-1997
  By the DEVise Development Group
  Madison, Wisconsin
  All Rights Reserved.
  ========================================================================

  Under no circumstances is this software to be copied, distributed,
  or altered in any way without prior permission from the DEVise
  Development Group.
*/

/*
  Implementation of Client (and CompDate) classes.
 */

/*
  $Id$

  $Log$
  Revision 1.3  1998/02/12 17:15:05  wenger
  Merged through collab_br_2; updated version number to 1.5.1.

  Revision 1.2.2.2  1998/02/02 08:24:08  liping
  Added CVS header

*/

/* 
** Copyright 1997 Collaborator Design Team
** 
** Permission to use, copy, modify, and distribute this software and its
** documentation for any purpose and without fee is hereby granted,
** provided that the above copyright notice appear in all copies and that
** both that copyright notice and this permission notice appear in
** supporting documentation, and that the names of the University of
** Wisconsin and the Collaborator Design Team not be used in advertising or
** publicity pertaining to distribution of the software without specific,
** written prior permission.  The University of Wisconsin and the Collaborator
** Design Team make no representations about the suitability of this
** software for any purpose.  It is provided "as is" without express
** or implied warranty.
** 
** THE UNIVERSITY OF WISCONSIN AND THE COLLABORATOR DESIGN TEAM DISCLAIM ALL
** WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES
** OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE UNIVERSITY OF
** WISCONSIN OR THE COLLABORATOR DESIGN TEAM BE LIABLE FOR ANY SPECIAL, 
** INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING 
** FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, 
** NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION 
** WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
** 
** Author:  Ashish Thusoo
** 	         University of Wisconsin, Computer Sciences Dept.
** 
*/ 
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVER_H_RPCGEN
#define	_SERVER_H_RPCGEN

#ifdef __cplusplus
extern "C" {
#endif

#include "CollabTypes.h"

#define	RPC_REGISTER 1
#define	RPC_DEREGISTER 2
#define	RPC_GROUPSEND 3
#define	RPC_LEADERSHIP 4
#define	RPC_GETCKPT 5
#define	RPC_EXECCKPT 6
#define RPC_QUERYGROUP 7

extern  int register_1(int fd, GroupKey *, ConnectInfo , int);
extern  int register_1_svc(int fd, GroupKey *, ConnectInfo , int);

extern  int deregister_1(int fd, GroupKey *, ConnectInfo , int);
extern  int deregister_1_svc(int fd, GroupKey *, ConnectInfo , int);

extern  int groupsend_1(int fd, GroupKey *, ConnectInfo , Msg);
extern  int groupsend_1_svc(GroupKey *, ConnectInfo , Msg);

extern  int querygroup_1(int fd, GroupKey *, ConnectInfo , char*&);
extern  int querygroup_1_svc(GroupKey *, ConnectInfo, char*&);

extern  int leadership_1(int fd, GroupKey *, ConnectInfo , int);
extern  int leadership_1_svc(GroupKey *, ConnectInfo , int);

extern  int getckpt_1(int fd, GroupKey *, ConnectInfo);
extern  int getckpt_1_svc(GroupKey *, ConnectInfo);

extern  int execckpt_1(int fd, GroupKey *, ConnectInfo);
extern  int execckpt_1_svc(GroupKey *, ConnectInfo);

extern int setnewleader_1_svc(GroupKey *);
#ifdef __cplusplus
}
#endif

#endif /* !_SERVER_H_RPCGEN */
