ARCH_FLAGS = -DSUN -g

VPATH = ../../graphics
include $(VPATH)/Makefile.base

depend:
	makedepend -I../../graphics $(VPATH)/*.c

# DO NOT DELETE THIS LINE -- make depend depends on it.

Action.o: ../../graphics/Action.h ../../graphics/DeviseTypes.h
Action.o: ../../graphics/Control.h ../../graphics/VisualArg.h
Action.o: ../../graphics/Color.h ../../graphics/DList.h ../../graphics/Exit.h
Action.o: ../../graphics/View.h ../../graphics/Dispatcher.h
Action.o: /usr/include/stdio.h ../../graphics/Journal.h
Action.o: ../../graphics/ViewWin.h ../../graphics/WindowRep.h
Action.o: ../../graphics/Geom.h /usr/include/math.h
Action.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
Action.o: ../../graphics/Transform.h ../../graphics/Pattern.h
Action.o: ../../graphics/DevisePixmap.h ../../graphics/Compress.h
Action.o: ../../graphics/ViewCallback.h ../../graphics/AttrList.h
Action.o: /usr/include/sys/time.h /usr/include/sys/time.h
Action.o: ../../graphics/Config.h ../../graphics/Cursor.h
ActionClassInfo.o: /usr/include/stdio.h ../../graphics/ActionClassInfo.h
ActionClassInfo.o: ../../graphics/DeviseTypes.h ../../graphics/ClassDir.h
ActionClassInfo.o: ../../graphics/Action.h ../../graphics/View.h
ActionClassInfo.o: ../../graphics/Dispatcher.h ../../graphics/DList.h
ActionClassInfo.o: ../../graphics/Exit.h ../../graphics/VisualArg.h
ActionClassInfo.o: ../../graphics/Color.h ../../graphics/Journal.h
ActionClassInfo.o: ../../graphics/ViewWin.h ../../graphics/WindowRep.h
ActionClassInfo.o: ../../graphics/Geom.h /usr/include/math.h
ActionClassInfo.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
ActionClassInfo.o: ../../graphics/Transform.h ../../graphics/Pattern.h
ActionClassInfo.o: ../../graphics/DevisePixmap.h ../../graphics/Compress.h
ActionClassInfo.o: ../../graphics/Control.h ../../graphics/ViewCallback.h
ActionClassInfo.o: ../../graphics/AttrList.h /usr/include/sys/time.h
ActionClassInfo.o: /usr/include/sys/time.h ../../graphics/Config.h
ActionClassInfo.o: ../../graphics/Cursor.h ../../graphics/Util.h
ActionClassInfo.o: /usr/include/assert.h /usr/include/stdlib.h
ActionClassInfo.o: /usr/include/sys/stdtypes.h /usr/include/strings.h
ActionClassInfo.o: /usr/include/ctype.h
AttrList.o: /usr/include/stdio.h ../../graphics/AttrList.h
AttrList.o: /usr/include/sys/time.h /usr/include/sys/time.h
AttrList.o: ../../graphics/DeviseTypes.h ../../graphics/Config.h
AttrList.o: ../../graphics/DList.h ../../graphics/Exit.h
AttrList.o: ../../graphics/Util.h /usr/include/assert.h /usr/include/stdlib.h
AttrList.o: /usr/include/sys/stdtypes.h /usr/include/strings.h
AttrList.o: /usr/include/ctype.h
AxisLabelClassInfo.o: /usr/include/stdio.h
AxisLabelClassInfo.o: ../../graphics/AxisLabelClassInfo.h
AxisLabelClassInfo.o: ../../graphics/DeviseTypes.h ../../graphics/ClassDir.h
AxisLabelClassInfo.o: ../../graphics/View.h ../../graphics/Dispatcher.h
AxisLabelClassInfo.o: ../../graphics/DList.h ../../graphics/Exit.h
AxisLabelClassInfo.o: ../../graphics/VisualArg.h ../../graphics/Color.h
AxisLabelClassInfo.o: ../../graphics/Journal.h ../../graphics/ViewWin.h
AxisLabelClassInfo.o: ../../graphics/WindowRep.h ../../graphics/Geom.h
AxisLabelClassInfo.o: /usr/include/math.h /usr/include/floatingpoint.h
AxisLabelClassInfo.o: /usr/include/sys/ieeefp.h ../../graphics/Transform.h
AxisLabelClassInfo.o: ../../graphics/Pattern.h ../../graphics/DevisePixmap.h
AxisLabelClassInfo.o: ../../graphics/Compress.h ../../graphics/Control.h
AxisLabelClassInfo.o: ../../graphics/ViewCallback.h ../../graphics/AttrList.h
AxisLabelClassInfo.o: /usr/include/sys/time.h /usr/include/sys/time.h
AxisLabelClassInfo.o: ../../graphics/Config.h ../../graphics/Cursor.h
AxisLabelClassInfo.o: ../../graphics/Util.h /usr/include/assert.h
AxisLabelClassInfo.o: /usr/include/stdlib.h /usr/include/sys/stdtypes.h
AxisLabelClassInfo.o: /usr/include/strings.h /usr/include/ctype.h
ClassDir.o: /usr/include/stdio.h ../../graphics/ClassDir.h
ClassDir.o: ../../graphics/DeviseTypes.h ../../graphics/Exit.h
ClassDir.o: ../../graphics/Util.h /usr/include/assert.h /usr/include/stdlib.h
ClassDir.o: /usr/include/sys/stdtypes.h /usr/include/sys/time.h
ClassDir.o: /usr/include/strings.h /usr/include/ctype.h
ColorMgr.o: ../../graphics/ColorMgr.h /usr/include/stdio.h
ColorMgr.o: ../../graphics/Color.h ../../graphics/Display.h
ColorMgr.o: ../../graphics/DeviseTypes.h ../../graphics/Geom.h
ColorMgr.o: /usr/include/math.h /usr/include/floatingpoint.h
ColorMgr.o: /usr/include/sys/ieeefp.h ../../graphics/Dispatcher.h
ColorMgr.o: ../../graphics/DList.h ../../graphics/Exit.h
ColorMgr.o: ../../graphics/VisualArg.h ../../graphics/Journal.h
Compress.o: /usr/include/stdio.h ../../graphics/Compress.h
Compress.o: ../../graphics/Exit.h
Control.o: ../../graphics/Init.h ../../graphics/DeviseTypes.h
Control.o: ../../graphics/BufPolicy.h ../../graphics/Control.h
Control.o: ../../graphics/VisualArg.h ../../graphics/Color.h
Control.o: ../../graphics/DList.h ../../graphics/Exit.h
Control.o: ../../graphics/XawControl.h ../../graphics/Dispatcher.h
Control.o: /usr/include/stdio.h ../../graphics/Journal.h
Control.o: ../../graphics/XawWidget.h /usr/include/X11/Intrinsic.h
Control.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
Control.o: /usr/include/sys/stdtypes.h /usr/include/sys/sysmacros.h
Control.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
Control.o: /usr/include/X11/Xosdefs.h /usr/include/stddef.h
Control.o: /usr/include/X11/Xutil.h /usr/include/X11/Xresource.h
Control.o: /usr/include/string.h /usr/include/X11/Core.h
Control.o: /usr/include/X11/Composite.h /usr/include/X11/Constraint.h
Control.o: /usr/include/X11/Object.h /usr/include/X11/RectObj.h
Control.o: /usr/include/X11/StringDefs.h /usr/include/X11/Xaw/Label.h
Control.o: /usr/include/X11/Xaw/Simple.h /usr/include/X11/Xmu/Converters.h
Control.o: /usr/include/X11/Xaw/Command.h /usr/include/X11/Xaw/Form.h
Control.o: /usr/include/X11/Xaw/Toggle.h /usr/include/X11/Xaw/List.h
Control.o: /usr/include/X11/Xaw/Viewport.h /usr/include/X11/Xaw/Reports.h
Control.o: /usr/include/X11/Xaw/AsciiText.h /usr/include/X11/Xaw/Text.h
Control.o: /usr/include/X11/Xaw/TextSink.h /usr/include/X11/Xaw/TextSrc.h
Control.o: /usr/include/X11/Xaw/AsciiSrc.h /usr/include/X11/Xaw/AsciiSink.h
Control.o: /usr/include/X11/Xaw/Repeater.h ../../graphics/StringArray.h
Control.o: ../../graphics/ClassDir.h ../../graphics/Util.h
Control.o: /usr/include/assert.h /usr/include/stdlib.h
Control.o: /usr/include/sys/time.h /usr/include/strings.h
Control.o: /usr/include/ctype.h
Cursor.o: ../../graphics/Cursor.h ../../graphics/DList.h
Cursor.o: ../../graphics/Exit.h ../../graphics/Color.h
Cursor.o: ../../graphics/VisualArg.h ../../graphics/DeviseTypes.h
Cursor.o: ../../graphics/ViewCallback.h ../../graphics/View.h
Cursor.o: ../../graphics/Dispatcher.h /usr/include/stdio.h
Cursor.o: ../../graphics/Journal.h ../../graphics/ViewWin.h
Cursor.o: ../../graphics/WindowRep.h ../../graphics/Geom.h
Cursor.o: /usr/include/math.h /usr/include/floatingpoint.h
Cursor.o: /usr/include/sys/ieeefp.h ../../graphics/Transform.h
Cursor.o: ../../graphics/Pattern.h ../../graphics/DevisePixmap.h
Cursor.o: ../../graphics/Compress.h ../../graphics/Control.h
Cursor.o: ../../graphics/AttrList.h /usr/include/sys/time.h
Cursor.o: /usr/include/sys/time.h ../../graphics/Config.h
CursorClassInfo.o: /usr/include/stdio.h ../../graphics/CursorClassInfo.h
CursorClassInfo.o: ../../graphics/ClassDir.h ../../graphics/DeviseTypes.h
CursorClassInfo.o: ../../graphics/VisualArg.h ../../graphics/Color.h
CursorClassInfo.o: ../../graphics/Cursor.h ../../graphics/DList.h
CursorClassInfo.o: ../../graphics/Exit.h ../../graphics/ViewCallback.h
CursorClassInfo.o: ../../graphics/Util.h /usr/include/assert.h
CursorClassInfo.o: /usr/include/stdlib.h /usr/include/sys/stdtypes.h
CursorClassInfo.o: /usr/include/sys/time.h /usr/include/strings.h
CursorClassInfo.o: /usr/include/ctype.h
DList.o: /usr/include/stdio.h ../../graphics/DList.h ../../graphics/Exit.h
DevisePixmap.o: /usr/include/stdio.h ../../graphics/Exit.h
DevisePixmap.o: ../../graphics/DevisePixmap.h ../../graphics/VisualArg.h
DevisePixmap.o: ../../graphics/DeviseTypes.h ../../graphics/Color.h
DevisePixmap.o: ../../graphics/Compress.h
Dispatcher.o: ../../graphics/Dispatcher.h /usr/include/stdio.h
Dispatcher.o: ../../graphics/DeviseTypes.h ../../graphics/DList.h
Dispatcher.o: ../../graphics/Exit.h ../../graphics/VisualArg.h
Dispatcher.o: ../../graphics/Color.h ../../graphics/Journal.h
Dispatcher.o: ../../graphics/Control.h ../../graphics/Init.h
Dispatcher.o: ../../graphics/BufPolicy.h ../../graphics/Selection.h
Dispatcher.o: ../../graphics/View.h ../../graphics/ViewWin.h
Dispatcher.o: ../../graphics/WindowRep.h ../../graphics/Geom.h
Dispatcher.o: /usr/include/math.h /usr/include/floatingpoint.h
Dispatcher.o: /usr/include/sys/ieeefp.h ../../graphics/Transform.h
Dispatcher.o: ../../graphics/Pattern.h ../../graphics/DevisePixmap.h
Dispatcher.o: ../../graphics/Compress.h ../../graphics/ViewCallback.h
Dispatcher.o: ../../graphics/AttrList.h /usr/include/sys/time.h
Dispatcher.o: /usr/include/sys/time.h ../../graphics/Config.h
Dispatcher.o: ../../graphics/Cursor.h ../../graphics/Time.h
Display.o: ../../graphics/XDisplay.h ../../graphics/Display.h
Display.o: ../../graphics/DeviseTypes.h ../../graphics/Geom.h
Display.o: /usr/include/math.h /usr/include/floatingpoint.h
Display.o: /usr/include/sys/ieeefp.h ../../graphics/Dispatcher.h
Display.o: /usr/include/stdio.h ../../graphics/DList.h ../../graphics/Exit.h
Display.o: ../../graphics/VisualArg.h ../../graphics/Color.h
Display.o: ../../graphics/Journal.h ../../graphics/ColorMgr.h
Display.o: ../../graphics/Xdef.h /usr/include/X11/Xlib.h
Display.o: /usr/include/sys/types.h /usr/include/sys/stdtypes.h
Display.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
Display.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
Display.o: /usr/include/stddef.h /usr/include/X11/Xutil.h
Display.o: ../../graphics/XBitmap.h ../../graphics/Pattern.h
Exit.o: ../../graphics/Exit.h /usr/include/stdio.h ../../graphics/Init.h
Exit.o: ../../graphics/DeviseTypes.h ../../graphics/BufPolicy.h
ExitClean.o: ../../graphics/Exit.h /usr/include/stdio.h
FilterQueue.o: /usr/include/stdio.h ../../graphics/Exit.h
FilterQueue.o: ../../graphics/FilterQueue.h ../../graphics/VisualArg.h
FilterQueue.o: ../../graphics/DeviseTypes.h ../../graphics/Color.h
Geom.o: ../../graphics/Geom.h ../../graphics/DeviseTypes.h
Geom.o: /usr/include/math.h /usr/include/floatingpoint.h
Geom.o: /usr/include/sys/ieeefp.h /usr/include/stdio.h
Init.o: /usr/include/stdio.h /usr/include/sys/types.h
Init.o: /usr/include/sys/stdtypes.h /usr/include/sys/sysmacros.h
Init.o: /usr/include/sys/stat.h /usr/include/unistd.h /usr/include/fcntl.h
Init.o: /usr/include/sys/fcntlcom.h /usr/include/strings.h
Init.o: /usr/include/signal.h /usr/include/sys/signal.h
Init.o: /usr/include/vm/faultcode.h ../../graphics/Dispatcher.h
Init.o: ../../graphics/DeviseTypes.h ../../graphics/DList.h
Init.o: ../../graphics/Exit.h ../../graphics/VisualArg.h
Init.o: ../../graphics/Color.h ../../graphics/Journal.h ../../graphics/Init.h
Init.o: ../../graphics/BufPolicy.h ../../graphics/Time.h
Init.o: /usr/include/sys/time.h /usr/include/sys/time.h
Init.o: ../../graphics/Timer.h ../../graphics/Util.h /usr/include/assert.h
Init.o: /usr/include/stdlib.h /usr/include/ctype.h
Journal.o: /usr/include/stdio.h /usr/include/sys/types.h
Journal.o: /usr/include/sys/stdtypes.h /usr/include/sys/sysmacros.h
Journal.o: /usr/include/unistd.h /usr/include/sys/stat.h /usr/include/fcntl.h
Journal.o: /usr/include/sys/fcntlcom.h /usr/include/limits.h
Journal.o: /usr/include/strings.h /usr/include/sys/time.h
Journal.o: ../../graphics/Journal.h ../../graphics/DeviseTypes.h
Journal.o: ../../graphics/VisualArg.h ../../graphics/Color.h
Journal.o: ../../graphics/Init.h ../../graphics/BufPolicy.h
Journal.o: ../../graphics/Selection.h ../../graphics/View.h
Journal.o: ../../graphics/Dispatcher.h ../../graphics/DList.h
Journal.o: ../../graphics/Exit.h ../../graphics/ViewWin.h
Journal.o: ../../graphics/WindowRep.h ../../graphics/Geom.h
Journal.o: /usr/include/math.h /usr/include/floatingpoint.h
Journal.o: /usr/include/sys/ieeefp.h ../../graphics/Transform.h
Journal.o: ../../graphics/Pattern.h ../../graphics/DevisePixmap.h
Journal.o: ../../graphics/Compress.h ../../graphics/Control.h
Journal.o: ../../graphics/ViewCallback.h ../../graphics/AttrList.h
Journal.o: /usr/include/sys/time.h ../../graphics/Config.h
Journal.o: ../../graphics/Cursor.h ../../graphics/Time.h
Parse.o: /usr/include/sys/types.h /usr/include/sys/stdtypes.h
Parse.o: /usr/include/sys/sysmacros.h /usr/include/sys/time.h
Parse.o: /usr/include/sys/time.h /usr/include/ctype.h /usr/include/stdio.h
Parse.o: ../../graphics/Config.h ../../graphics/Exit.h
ParseCat.o: /usr/include/stdio.h ../../graphics/ParseCat.h
ParseCat.o: ../../graphics/DeviseTypes.h ../../graphics/ClassDir.h
ParseCat.o: ../../graphics/AttrList.h /usr/include/sys/time.h
ParseCat.o: /usr/include/sys/time.h ../../graphics/Config.h
ParseCat.o: ../../graphics/DList.h ../../graphics/Exit.h
ParseCat.o: ../../graphics/Parse.h ../../graphics/Control.h
ParseCat.o: ../../graphics/VisualArg.h ../../graphics/Color.h
ParseCat.o: ../../graphics/Util.h /usr/include/assert.h /usr/include/stdlib.h
ParseCat.o: /usr/include/sys/stdtypes.h /usr/include/strings.h
ParseCat.o: /usr/include/ctype.h
Selection.o: /usr/include/strings.h /usr/include/stdio.h
Selection.o: ../../graphics/Selection.h ../../graphics/View.h
Selection.o: ../../graphics/DeviseTypes.h ../../graphics/Dispatcher.h
Selection.o: ../../graphics/DList.h ../../graphics/Exit.h
Selection.o: ../../graphics/VisualArg.h ../../graphics/Color.h
Selection.o: ../../graphics/Journal.h ../../graphics/ViewWin.h
Selection.o: ../../graphics/WindowRep.h ../../graphics/Geom.h
Selection.o: /usr/include/math.h /usr/include/floatingpoint.h
Selection.o: /usr/include/sys/ieeefp.h ../../graphics/Transform.h
Selection.o: ../../graphics/Pattern.h ../../graphics/DevisePixmap.h
Selection.o: ../../graphics/Compress.h ../../graphics/Control.h
Selection.o: ../../graphics/ViewCallback.h ../../graphics/AttrList.h
Selection.o: /usr/include/sys/time.h /usr/include/sys/time.h
Selection.o: ../../graphics/Config.h ../../graphics/Cursor.h
Time.o: ../../graphics/Time.h /usr/include/sys/time.h /usr/include/sys/time.h
Time.o: ../../graphics/Journal.h ../../graphics/DeviseTypes.h
Time.o: ../../graphics/VisualArg.h ../../graphics/Color.h
TimeStamp.o: ../../graphics/TimeStamp.h
Timer.o: /usr/include/stdio.h /usr/include/sys/time.h /usr/include/sys/time.h
Timer.o: /usr/include/signal.h /usr/include/sys/signal.h
Timer.o: /usr/include/vm/faultcode.h ../../graphics/Timer.h
Timer.o: ../../graphics/DeviseTypes.h
Util.o: /usr/include/sys/types.h /usr/include/sys/stdtypes.h
Util.o: /usr/include/sys/sysmacros.h /usr/include/stdio.h
Util.o: /usr/include/sys/stat.h /usr/include/sys/dir.h /usr/include/unistd.h
Util.o: ../../graphics/Util.h /usr/include/assert.h /usr/include/stdlib.h
Util.o: /usr/include/sys/time.h /usr/include/strings.h /usr/include/ctype.h
Util.o: ../../graphics/Exit.h
View.o: /usr/include/sys/time.h ../../graphics/Util.h /usr/include/assert.h
View.o: /usr/include/stdlib.h /usr/include/sys/stdtypes.h
View.o: /usr/include/strings.h /usr/include/ctype.h ../../graphics/View.h
View.o: ../../graphics/DeviseTypes.h ../../graphics/Dispatcher.h
View.o: /usr/include/stdio.h ../../graphics/DList.h ../../graphics/Exit.h
View.o: ../../graphics/VisualArg.h ../../graphics/Color.h
View.o: ../../graphics/Journal.h ../../graphics/ViewWin.h
View.o: ../../graphics/WindowRep.h ../../graphics/Geom.h /usr/include/math.h
View.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
View.o: ../../graphics/Transform.h ../../graphics/Pattern.h
View.o: ../../graphics/DevisePixmap.h ../../graphics/Compress.h
View.o: ../../graphics/Control.h ../../graphics/ViewCallback.h
View.o: ../../graphics/AttrList.h /usr/include/sys/time.h
View.o: ../../graphics/Config.h ../../graphics/Cursor.h
View.o: ../../graphics/Action.h ../../graphics/FilterQueue.h
View.o: ../../graphics/TimeStamp.h ../../graphics/Parse.h
ViewWin.o: /usr/include/stdio.h ../../graphics/ViewWin.h
ViewWin.o: ../../graphics/DList.h ../../graphics/Exit.h
ViewWin.o: ../../graphics/DeviseTypes.h ../../graphics/WindowRep.h
ViewWin.o: ../../graphics/Geom.h /usr/include/math.h
ViewWin.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
ViewWin.o: ../../graphics/Transform.h ../../graphics/Color.h
ViewWin.o: ../../graphics/Pattern.h ../../graphics/DevisePixmap.h
ViewWin.o: ../../graphics/VisualArg.h ../../graphics/Compress.h
ViewWin.o: ../../graphics/Display.h ../../graphics/Dispatcher.h
ViewWin.o: ../../graphics/Journal.h ../../graphics/ColorMgr.h
ViewWinHor.o: ../../graphics/ViewWinHor.h ../../graphics/ViewWin.h
ViewWinHor.o: ../../graphics/DList.h ../../graphics/Exit.h
ViewWinHor.o: ../../graphics/DeviseTypes.h ../../graphics/WindowRep.h
ViewWinHor.o: /usr/include/stdio.h ../../graphics/Geom.h /usr/include/math.h
ViewWinHor.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
ViewWinHor.o: ../../graphics/Transform.h ../../graphics/Color.h
ViewWinHor.o: ../../graphics/Pattern.h ../../graphics/DevisePixmap.h
ViewWinHor.o: ../../graphics/VisualArg.h ../../graphics/Compress.h
ViewWinVer.o: ../../graphics/ViewWinVer.h ../../graphics/ViewWin.h
ViewWinVer.o: ../../graphics/DList.h ../../graphics/Exit.h
ViewWinVer.o: ../../graphics/DeviseTypes.h ../../graphics/WindowRep.h
ViewWinVer.o: /usr/include/stdio.h ../../graphics/Geom.h /usr/include/math.h
ViewWinVer.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
ViewWinVer.o: ../../graphics/Transform.h ../../graphics/Color.h
ViewWinVer.o: ../../graphics/Pattern.h ../../graphics/DevisePixmap.h
ViewWinVer.o: ../../graphics/VisualArg.h ../../graphics/Compress.h
ViewWinVer.o: ../../graphics/Display.h ../../graphics/Dispatcher.h
ViewWinVer.o: ../../graphics/Journal.h ../../graphics/ColorMgr.h
VisualLink.o: ../../graphics/VisualLink.h ../../graphics/DList.h
VisualLink.o: ../../graphics/Exit.h ../../graphics/Dispatcher.h
VisualLink.o: /usr/include/stdio.h ../../graphics/DeviseTypes.h
VisualLink.o: ../../graphics/VisualArg.h ../../graphics/Color.h
VisualLink.o: ../../graphics/Journal.h ../../graphics/View.h
VisualLink.o: ../../graphics/ViewWin.h ../../graphics/WindowRep.h
VisualLink.o: ../../graphics/Geom.h /usr/include/math.h
VisualLink.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
VisualLink.o: ../../graphics/Transform.h ../../graphics/Pattern.h
VisualLink.o: ../../graphics/DevisePixmap.h ../../graphics/Compress.h
VisualLink.o: ../../graphics/Control.h ../../graphics/ViewCallback.h
VisualLink.o: ../../graphics/AttrList.h /usr/include/sys/time.h
VisualLink.o: /usr/include/sys/time.h ../../graphics/Config.h
VisualLink.o: ../../graphics/Cursor.h
VisualLinkClassInfo.o: /usr/include/stdio.h ../../graphics/VisualLink.h
VisualLinkClassInfo.o: ../../graphics/DList.h ../../graphics/Exit.h
VisualLinkClassInfo.o: ../../graphics/Dispatcher.h
VisualLinkClassInfo.o: ../../graphics/DeviseTypes.h
VisualLinkClassInfo.o: ../../graphics/VisualArg.h ../../graphics/Color.h
VisualLinkClassInfo.o: ../../graphics/Journal.h ../../graphics/View.h
VisualLinkClassInfo.o: ../../graphics/ViewWin.h ../../graphics/WindowRep.h
VisualLinkClassInfo.o: ../../graphics/Geom.h /usr/include/math.h
VisualLinkClassInfo.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
VisualLinkClassInfo.o: ../../graphics/Transform.h ../../graphics/Pattern.h
VisualLinkClassInfo.o: ../../graphics/DevisePixmap.h
VisualLinkClassInfo.o: ../../graphics/Compress.h ../../graphics/Control.h
VisualLinkClassInfo.o: ../../graphics/ViewCallback.h
VisualLinkClassInfo.o: ../../graphics/AttrList.h /usr/include/sys/time.h
VisualLinkClassInfo.o: /usr/include/sys/time.h ../../graphics/Config.h
VisualLinkClassInfo.o: ../../graphics/Cursor.h
VisualLinkClassInfo.o: ../../graphics/VisualLinkClassInfo.h
VisualLinkClassInfo.o: ../../graphics/ClassDir.h ../../graphics/Util.h
VisualLinkClassInfo.o: /usr/include/assert.h /usr/include/stdlib.h
VisualLinkClassInfo.o: /usr/include/sys/stdtypes.h /usr/include/strings.h
VisualLinkClassInfo.o: /usr/include/ctype.h
WinClassInfo.o: ../../graphics/Display.h ../../graphics/DeviseTypes.h
WinClassInfo.o: ../../graphics/Geom.h /usr/include/math.h
WinClassInfo.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
WinClassInfo.o: ../../graphics/Dispatcher.h /usr/include/stdio.h
WinClassInfo.o: ../../graphics/DList.h ../../graphics/Exit.h
WinClassInfo.o: ../../graphics/VisualArg.h ../../graphics/Color.h
WinClassInfo.o: ../../graphics/Journal.h ../../graphics/ColorMgr.h
WinClassInfo.o: ../../graphics/Control.h ../../graphics/WinClassInfo.h
WinClassInfo.o: ../../graphics/ClassDir.h ../../graphics/ViewWinVer.h
WinClassInfo.o: ../../graphics/ViewWin.h ../../graphics/WindowRep.h
WinClassInfo.o: ../../graphics/Transform.h ../../graphics/Pattern.h
WinClassInfo.o: ../../graphics/DevisePixmap.h ../../graphics/Compress.h
WinClassInfo.o: ../../graphics/Util.h /usr/include/assert.h
WinClassInfo.o: /usr/include/stdlib.h /usr/include/sys/stdtypes.h
WinClassInfo.o: /usr/include/sys/time.h /usr/include/strings.h
WinClassInfo.o: /usr/include/ctype.h
WindowRep.o: ../../graphics/WindowRep.h /usr/include/stdio.h
WindowRep.o: ../../graphics/Geom.h ../../graphics/DeviseTypes.h
WindowRep.o: /usr/include/math.h /usr/include/floatingpoint.h
WindowRep.o: /usr/include/sys/ieeefp.h ../../graphics/Transform.h
WindowRep.o: ../../graphics/DList.h ../../graphics/Exit.h
WindowRep.o: ../../graphics/Color.h ../../graphics/Pattern.h
WindowRep.o: ../../graphics/DevisePixmap.h ../../graphics/VisualArg.h
WindowRep.o: ../../graphics/Compress.h ../../graphics/Display.h
WindowRep.o: ../../graphics/Dispatcher.h ../../graphics/Journal.h
WindowRep.o: ../../graphics/ColorMgr.h
XBitmap.o: ../../graphics/XBitmap.h
XDisplay.o: /usr/include/X11/Intrinsic.h /usr/include/X11/Xlib.h
XDisplay.o: /usr/include/sys/types.h /usr/include/sys/stdtypes.h
XDisplay.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
XDisplay.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
XDisplay.o: /usr/include/stddef.h /usr/include/X11/Xutil.h
XDisplay.o: /usr/include/X11/Xresource.h /usr/include/string.h
XDisplay.o: /usr/include/X11/Core.h /usr/include/X11/Composite.h
XDisplay.o: /usr/include/X11/Constraint.h /usr/include/X11/Object.h
XDisplay.o: /usr/include/X11/RectObj.h ../../graphics/XDisplay.h
XDisplay.o: ../../graphics/Display.h ../../graphics/DeviseTypes.h
XDisplay.o: ../../graphics/Geom.h /usr/include/math.h
XDisplay.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
XDisplay.o: ../../graphics/Dispatcher.h /usr/include/stdio.h
XDisplay.o: ../../graphics/DList.h ../../graphics/Exit.h
XDisplay.o: ../../graphics/VisualArg.h ../../graphics/Color.h
XDisplay.o: ../../graphics/Journal.h ../../graphics/ColorMgr.h
XDisplay.o: ../../graphics/Xdef.h ../../graphics/XBitmap.h
XDisplay.o: ../../graphics/Pattern.h ../../graphics/XWindowRep.h
XDisplay.o: ../../graphics/WindowRep.h ../../graphics/Transform.h
XDisplay.o: ../../graphics/DevisePixmap.h ../../graphics/Compress.h
XDisplay.o: /usr/include/strings.h ../../graphics/Control.h
XDisplay.o: ../../graphics/Init.h ../../graphics/BufPolicy.h
XWindowRep.o: ../../graphics/Init.h ../../graphics/DeviseTypes.h
XWindowRep.o: ../../graphics/BufPolicy.h ../../graphics/XWindowRep.h
XWindowRep.o: ../../graphics/WindowRep.h /usr/include/stdio.h
XWindowRep.o: ../../graphics/Geom.h /usr/include/math.h
XWindowRep.o: /usr/include/floatingpoint.h /usr/include/sys/ieeefp.h
XWindowRep.o: ../../graphics/Transform.h ../../graphics/DList.h
XWindowRep.o: ../../graphics/Exit.h ../../graphics/Color.h
XWindowRep.o: ../../graphics/Pattern.h ../../graphics/DevisePixmap.h
XWindowRep.o: ../../graphics/VisualArg.h ../../graphics/Compress.h
XWindowRep.o: ../../graphics/Xdef.h /usr/include/X11/Xlib.h
XWindowRep.o: /usr/include/sys/types.h /usr/include/sys/stdtypes.h
XWindowRep.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
XWindowRep.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
XWindowRep.o: /usr/include/stddef.h /usr/include/X11/Xutil.h
XWindowRep.o: /usr/include/strings.h ../../graphics/XDisplay.h
XWindowRep.o: ../../graphics/Display.h ../../graphics/Dispatcher.h
XWindowRep.o: ../../graphics/Journal.h ../../graphics/ColorMgr.h
XWindowRep.o: ../../graphics/XBitmap.h
XawControl.o: /usr/include/stdio.h ../../graphics/XawControl.h
XawControl.o: ../../graphics/Control.h ../../graphics/DeviseTypes.h
XawControl.o: ../../graphics/VisualArg.h ../../graphics/Color.h
XawControl.o: ../../graphics/DList.h ../../graphics/Exit.h
XawControl.o: ../../graphics/Dispatcher.h ../../graphics/Journal.h
XawControl.o: ../../graphics/XawWidget.h /usr/include/X11/Intrinsic.h
XawControl.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
XawControl.o: /usr/include/sys/stdtypes.h /usr/include/sys/sysmacros.h
XawControl.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
XawControl.o: /usr/include/X11/Xosdefs.h /usr/include/stddef.h
XawControl.o: /usr/include/X11/Xutil.h /usr/include/X11/Xresource.h
XawControl.o: /usr/include/string.h /usr/include/X11/Core.h
XawControl.o: /usr/include/X11/Composite.h /usr/include/X11/Constraint.h
XawControl.o: /usr/include/X11/Object.h /usr/include/X11/RectObj.h
XawControl.o: /usr/include/X11/StringDefs.h /usr/include/X11/Xaw/Label.h
XawControl.o: /usr/include/X11/Xaw/Simple.h /usr/include/X11/Xmu/Converters.h
XawControl.o: /usr/include/X11/Xaw/Command.h /usr/include/X11/Xaw/Form.h
XawControl.o: /usr/include/X11/Xaw/Toggle.h /usr/include/X11/Xaw/List.h
XawControl.o: /usr/include/X11/Xaw/Viewport.h /usr/include/X11/Xaw/Reports.h
XawControl.o: /usr/include/X11/Xaw/AsciiText.h /usr/include/X11/Xaw/Text.h
XawControl.o: /usr/include/X11/Xaw/TextSink.h /usr/include/X11/Xaw/TextSrc.h
XawControl.o: /usr/include/X11/Xaw/AsciiSrc.h
XawControl.o: /usr/include/X11/Xaw/AsciiSink.h
XawControl.o: /usr/include/X11/Xaw/Repeater.h ../../graphics/Xdef.h
XawControl.o: /usr/include/X11/Shell.h /usr/include/sys/time.h
XawControl.o: /usr/include/sys/time.h /usr/include/sys/resource.h
XawWidget.o: ../../graphics/XawWidget.h /usr/include/stdio.h
XawWidget.o: /usr/include/X11/Intrinsic.h /usr/include/X11/Xlib.h
XawWidget.o: /usr/include/sys/types.h /usr/include/sys/stdtypes.h
XawWidget.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
XawWidget.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
XawWidget.o: /usr/include/stddef.h /usr/include/X11/Xutil.h
XawWidget.o: /usr/include/X11/Xresource.h /usr/include/string.h
XawWidget.o: /usr/include/X11/Core.h /usr/include/X11/Composite.h
XawWidget.o: /usr/include/X11/Constraint.h /usr/include/X11/Object.h
XawWidget.o: /usr/include/X11/RectObj.h /usr/include/X11/StringDefs.h
XawWidget.o: /usr/include/X11/Xaw/Label.h /usr/include/X11/Xaw/Simple.h
XawWidget.o: /usr/include/X11/Xmu/Converters.h /usr/include/X11/Xaw/Command.h
XawWidget.o: /usr/include/X11/Xaw/Form.h /usr/include/X11/Xaw/Toggle.h
XawWidget.o: /usr/include/X11/Xaw/List.h /usr/include/X11/Xaw/Viewport.h
XawWidget.o: /usr/include/X11/Xaw/Reports.h /usr/include/X11/Xaw/AsciiText.h
XawWidget.o: /usr/include/X11/Xaw/Text.h /usr/include/X11/Xaw/TextSink.h
XawWidget.o: /usr/include/X11/Xaw/TextSrc.h /usr/include/X11/Xaw/AsciiSrc.h
XawWidget.o: /usr/include/X11/Xaw/AsciiSink.h /usr/include/X11/Xaw/Repeater.h
XawWidget.o: ../../graphics/DeviseTypes.h ../../graphics/DList.h
XawWidget.o: ../../graphics/Exit.h
jstat.o: /usr/include/math.h /usr/include/floatingpoint.h
jstat.o: /usr/include/sys/ieeefp.h ../../graphics/Journal.h
jstat.o: ../../graphics/DeviseTypes.h ../../graphics/VisualArg.h
jstat.o: ../../graphics/Color.h
test.o: /usr/include/stdio.h /usr/include/sys/time.h ../../graphics/Util.h
test.o: /usr/include/assert.h /usr/include/stdlib.h
test.o: /usr/include/sys/stdtypes.h /usr/include/strings.h
test.o: /usr/include/ctype.h
testAtof.o: ../../graphics/Util.h /usr/include/assert.h /usr/include/stdlib.h
testAtof.o: /usr/include/sys/stdtypes.h /usr/include/sys/time.h
testAtof.o: /usr/include/strings.h /usr/include/ctype.h
testView.o: /usr/include/stdio.h ../../graphics/Init.h
testView.o: ../../graphics/DeviseTypes.h ../../graphics/BufPolicy.h
testView.o: ../../graphics/ViewWinVer.h ../../graphics/ViewWin.h
testView.o: ../../graphics/DList.h ../../graphics/Exit.h
testView.o: ../../graphics/WindowRep.h ../../graphics/Geom.h
testView.o: /usr/include/math.h /usr/include/floatingpoint.h
testView.o: /usr/include/sys/ieeefp.h ../../graphics/Transform.h
testView.o: ../../graphics/Color.h ../../graphics/Pattern.h
testView.o: ../../graphics/DevisePixmap.h ../../graphics/VisualArg.h
testView.o: ../../graphics/Compress.h ../../graphics/View.h
testView.o: ../../graphics/Dispatcher.h ../../graphics/Journal.h
testView.o: ../../graphics/Control.h ../../graphics/ViewCallback.h
testView.o: ../../graphics/AttrList.h /usr/include/sys/time.h
testView.o: /usr/include/sys/time.h ../../graphics/Config.h
testView.o: ../../graphics/Cursor.h ../../graphics/Action.h
testViewWin.o: ../../graphics/Dispatcher.h /usr/include/stdio.h
testViewWin.o: ../../graphics/DeviseTypes.h ../../graphics/DList.h
testViewWin.o: ../../graphics/Exit.h ../../graphics/VisualArg.h
testViewWin.o: ../../graphics/Color.h ../../graphics/Journal.h
testViewWin.o: ../../graphics/ViewWinVer.h ../../graphics/ViewWin.h
testViewWin.o: ../../graphics/WindowRep.h ../../graphics/Geom.h
testViewWin.o: /usr/include/math.h /usr/include/floatingpoint.h
testViewWin.o: /usr/include/sys/ieeefp.h ../../graphics/Transform.h
testViewWin.o: ../../graphics/Pattern.h ../../graphics/DevisePixmap.h
testViewWin.o: ../../graphics/Compress.h ../../graphics/ViewWinHor.h
testWindowRep.o: /usr/include/stdio.h ../../graphics/Dispatcher.h
testWindowRep.o: ../../graphics/DeviseTypes.h ../../graphics/DList.h
testWindowRep.o: ../../graphics/Exit.h ../../graphics/VisualArg.h
testWindowRep.o: ../../graphics/Color.h ../../graphics/Journal.h
testWindowRep.o: ../../graphics/Display.h ../../graphics/Geom.h
testWindowRep.o: /usr/include/math.h /usr/include/floatingpoint.h
testWindowRep.o: /usr/include/sys/ieeefp.h ../../graphics/ColorMgr.h
testWindowRep.o: ../../graphics/WindowRep.h ../../graphics/Transform.h
testWindowRep.o: ../../graphics/Pattern.h ../../graphics/DevisePixmap.h
testWindowRep.o: ../../graphics/Compress.h
