#! /bin/csh -f

#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1992-1996
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  $Id$

#  $Log$
#  Revision 1.3  1996/01/23 22:08:03  jussi
#  Added copyright notice.
#

############################################################

echo Buffer Manager:
echo -n "  "
wc graphics/Buf*.[Cch] graphics.new/Buf*.[Cch] | tail -1

echo Query Processor:
echo -n "  "
wc graphics.new/Query*.[Cch] | tail -1

echo View Support:
echo -n "  "
wc graphics/View*.[Cch] | tail -1

echo TData and GData Support:
echo -n "  "
wc graphics.new/[GT]Data*.[Cch] graphics.new/Map*.[Cch] | tail -1

echo Mapping Support:
echo -n "  "
wc graphics.new/Map*.[Cch] | tail -1

echo XWindows and Generic Display Support:
echo -n "  "
wc graphics/*Win*.[Cch] graphics/*Display*.[Cch] graphics/X*.[Cch] | tail -1

echo Visual Links and Cursors:
echo -n "  "
wc graphics/*Link*.[Cch] graphics/*Cursor*.[Cch] | tail -1

echo Ams, Generic, and Multi Applications:
echo -n "  "
wc ams/*.[Cch] generic/*.[Cch] multi/*.[Cch] | tail -1

echo CompuStat, CRSP, and ISSM Interfaces:
echo -n "  "
wc compustat/*.[Cch] crsp/*.[Cch] issm/*.[Cch] | tail -1

echo Statistics Support:
echo -n "  "
wc graphics.new/*Stat*.[Cch] graphics.new/*KGraph*.[Cch] | tail -1

echo Control Panel and Dispatcher:
echo -n "  "
wc graphics/Control*.[Cch] graphics.new/TkControl*.[Cch] | tail -1

echo Parser for Compiled Mapping:
echo -n "  "
wc parser/*.[Cch] parser/*.y parser/*.lex | tail -1

echo Tape Interface:
echo -n "  "
wc tape/*.[Cch] | tail -1

echo User Interface:
echo -n "  "
wc lib/*.tk lib/*.tcl lib/*.txt | tail -1

echo Documentation:
echo -n "  "
wc doc/*.tex doc/Agreement doc/Copyright doc/Disclaimer | tail -1

echo Utilities:
echo -n "  "
wc util/*.[Cch] | tail -1

echo Makefiles:
echo -n "  "
wc */Makefile.base */*/Makefile | tail -1

echo All Files:
echo -n "  "
wc */*.[Cch] */*/Makefile */Makefile.base */*.lex */*.y */*.tk */*.tcl | tail -1
