#! /bin/csh -f

#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1992-1996
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  $Id$

#  $Log$
#  Revision 1.7  1996/08/01 18:17:44  jussi
#  Added sunx86_55 platform.
#
#  Revision 1.6  1996/07/23 17:31:36  jussi
#  Added Ultrix and Alpha/OSF platforms.
#
#  Revision 1.5  1996/05/16 19:47:30  jussi
#  Minor fixes.
#
#  Revision 1.4  1996/05/16 19:38:52  jussi
#  Added AIX and Solaris/Sparc.
#
#  Revision 1.3  1996/03/27 18:26:07  wenger
#  Changes to get DEVise to compile and run on Linux.
#
#  Revision 1.2  1996/01/23 22:09:00  jussi
#  Added copyright notice.
#

############################################################

cd run

if (! -d bin) then
  ln -s '@sys' bin
endif

if (! -d sunx86_55) then
  ln -s ../solaris sunx86_55
endif

if (! -d sunx86_54) then
  ln -s ../solaris sunx86_54
endif

if (! -d sun4m_54) then
  ln -s ../solsparc sun4m_54
endif

if (! -d sun4m_412) then
  ln -s ../sun sun4m_412
endif

if (! -d hp700_ux90) then
  ln -s ../hp hp700_ux90
endif

if (! -d rs_aix32) then
  ln -s ../aix rs_aix32
endif

if (! -d alpha_osf20) then
  ln -s ../alpha_osf20 .
endif

if (! -d pmax_ul43a) then
  ln -s ../pmax_ul43a .
endif

ln -fs /p/devise/dat/*.idx . >& /dev/null
ln -fs /p/devise/dat/dsi94.dat . >& /dev/null

cd ../solsparc
ln -s ../solaris/Makefile . >& /dev/null
cd ../sun
ln -s ../solaris/Makefile . >& /dev/null
cd ../hp
ln -s ../solaris/Makefile . >& /dev/null
cd ../sgi
ln -s ../solaris/Makefile . >& /dev/null
cd ../linux
ln -s ../solaris/Makefile . >& /dev/null
cd ../aix
ln -s ../solaris/Makefile . >& /dev/null
cd ../alpha_osf20
ln -s ../solaris/Makefile . >& /dev/null
cd ../pmax_ul43a
ln -s ../solaris/Makefile . >& /dev/null

cd ..

cd aix/cslib
ln -s ../../cslib/client.tcl . >& /dev/null
cd ../../alpha_osf20/cslib
ln -s ../../cslib/client.tcl . >& /dev/null
cd ../../hp/cslib
ln -s ../../cslib/client.tcl . >& /dev/null
cd ../../linux/cslib
ln -s ../../cslib/client.tcl . >& /dev/null
cd ../../pmax_ul43a/cslib
ln -s ../../cslib/client.tcl . >& /dev/null
cd ../../sgi/cslib
ln -s ../../cslib/client.tcl . >& /dev/null
cd ../../solaris/cslib
ln -s ../../cslib/client.tcl . >& /dev/null
cd ../../solsparc/cslib
ln -s ../../cslib/client.tcl . >& /dev/null
cd ../../sun/cslib
ln -s ../../cslib/client.tcl . >& /dev/null

cd ../..
