#! /bin/csh -f

#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1992-1996
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  $Id$

#  $Log$

############################################################

cd run

if (! -f bin) then
  ln -s '@sys' bin
endif

if (! -f sunx86_54) then
  ln -s ../solaris sunx86_54
endif

if (! -d sun4m_412) then
  ln -s ../sun sun4m_412
endif

if (! -d hp700_ux90) then
  ln -s ../hp hp700_ux90
endif

ln -fs /p/devise/dat/*.idx .

cd ../sun
ln -s ../solaris/Makefile .
cd ../hp
ln -s ../solaris/Makefile .
cd ../sgi
ln -s ../solaris/Makefile .

cd ..
