#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1992-1996
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  $Id$

#  $Log$
#  Revision 1.23  1997/06/13 18:55:32  wenger
#  Added stuff for xvertext library.
#
#  Revision 1.22  1997/05/28 15:40:25  wenger
#  Merged Shilpa's layout manager code through the layout_mgr_branch_2 tag.
#
#  Revision 1.21.4.1  1997/05/21 14:51:42  ssl
#  Fixed compile problem with multi
#
#  Revision 1.21  1997/04/30 21:45:51  wenger
#  Fixed non-constant strings in complex mappings bug; TDataAsciiInterp
#  no longer gives warning message on blank data lines; added makefile
#  targets to make a Purify'd version of multi; fixed uninitialized memory
#  read in the DList code; fixed bug that caused 1.4 version of multi to
#  always crash; better error messages in DTE command parser; version is
#  now 1.4.4.
#
#  Revision 1.20  1997/04/04 15:44:58  wenger
#  Set up makefiles to allow making a 'profile' version of Devise.
#
#  Revision 1.19  1996/12/23 17:00:35  donjerko
#  Moved -ldte behind -lgraphics
#
#  Revision 1.18  1996/11/18 18:13:40  donjerko
#  Added final touches for DTE
#
#  Revision 1.17  1996/08/06 20:12:13  wenger
#  Set up makefiles to easily compile with -g flag; other cleanup of
#  makefiles.
#
#  Revision 1.16  1996/08/05 19:51:59  wenger
#  Fixed compile errors caused by some of Kevin's recent changes; changed
#  the attrproj stuff to make a .a file instead of a .o; added some more
#  TData file writing stuff; misc. cleanup.
#
#  Revision 1.15  1996/07/18 14:19:59  jussi
#  Replaced name libgraphics.new.a with libgraphicsnew.a.
#
#  Revision 1.14  1996/07/09 16:01:05  wenger
#  Added master version number and compile date to C++ code (also displayed
#  in the user interface); added -usage and -version command line arguments;
#  updated usage message.
#
#  Revision 1.13  1996/07/08 18:15:18  wenger
#  Fixed multi makefiles with ARCH_SYSLIBS macro like generic so that
#  multi will compile for HP.
#
#  Revision 1.12  1996/05/22 21:16:44  jussi
#  Changed Devise from using composite .o files to using .a files.
#  The old approach did not work in AIX whereas the new approach
#  is more portable. Also, the graphics library is no longer
#  included in the graphics.new library, which yields some space
#  savings.

############################################################

include ../../Makefile.common

CFLAGS = $(ARCH_FLAGS) -I../../graphics -I../../graphics.new -I../../tape \
	-fexternal-templates -Wall -Wno-unused $(OPTFLAG) -DUNIX

# Kevin created a dependency that means that graphicsnew must be included
# twice below.
LDFLAGS = $(ARCH_LDFLAGS) \
	-L../graphics.new -L../graphics -L../tape -L../issm -L../DTE \
	 -L../LM -L../xvertext \
	-L../crsp -L../compustat -lmonolith -lgraphicsnew -lgraphics \
	-lgraphicsnew -ldte -llm -lXrot \
	-lissm -lcrsp -lcstat -ltape \
	-L$(PERL_CORE) -lperl -L../unidata -lunidata $(ARCH_SYSLIBS) \
	$(ARCH_LDPOST)

# Set up for profiling.
ifneq ($(DEV_PROFILE),)
        ARCH_LDPOST  += -ldl
endif

ALLSRC = disp.c TDataMulti.c TDataHost.c TDataCycle.c Message.c \
	MappingClassInfo.c HostMappingClassInfo.c \
	CycleOccMappingClassInfo.c \
	CycleEffMappingClassInfo.c \
	CycleWorkingMappingClassInfo.c \
	CycleSuspendedMappingClassInfo.c \
	CycleCpuTimeMappingClassInfo.c

ALLOBJ = $(ALLSRC:.c=.o)

ALLLIBS = ../graphics/libgraphics.a ../graphics.new/libgraphicsnew.a \
	../tape/libtape.a ../issm/libissm.a ../compustat/libcstat.a \
	../crsp/libcrsp.a ../graphics.new/libmonolith.a \
	../LM/liblm.a ../xvertext/libXrot.a


all: disp
pure: disp.pure

# Note: the line below forces CompDate.c to always be compiled.
FORCE_DATE = $(CC) -c $(CFLAGS) ../../generic/CompDate.c

MULTI = $(CC) -o $@ $(ALLOBJ) CompDate.o $(LDFLAGS)

disp: $(ALLOBJ) $(ALLLIBS)
	$(FORCE_DATE)
	$(MULTI)

disp.pure: $(ALLOBJ) $(ALLLIBS)
	$(FORCE_DATE)
	$(PURIFY) $(PURE_OPT) $(MULTI)

mapefile.h: map
	../parser/parser -o $@ < $?

map_host.h: map_host
	../parser/parser -o $@ < $?

map_cycle_cpu_time.h: map_cycle_cpu_time
	../parser/parser -o $@ < $?

map_cycle_eff.h: map_cycle_eff
	../parser/parser -o $@ < $?

map_cycle_occ.h: map_cycle_occ
	../parser/parser -o $@ < $?

map_cycle_working.h: map_cycle_working
	../parser/parser -o $@ < $?

map_cycle_susp.h: map_cycle_susp
	../parser/parser -o $@ < $?

.PHONY: clean mostlyclean

clean: mostlyclean
	-rm disp

mostlyclean:
	-rm $(ALLOBJ) CompDate.o
