#! /bin/csh -f

#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 2007
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  Install the "upload and visualize data" part of the
#  peptide-cgi setup.

############################################################

#  $Id$

############################################################

#-----------------------------------------------------------
# Check and get the arguments.

if ($#argv != 5) then
  echo "Usage: install_uvd <uvd_session_home> <uvd_data_home> <uvd_html_home>"
  echo "  <uvd_data_upload> <cgi_home>"
  exit 1
endif

set sessionhome = $1
set datahome = $2
set htmlhome = $3
set uploadhome = $4
set cgihome = $5

#-----------------------------------------------------------

# Make the UVD session, data, and html directories.
mkdir -p $sessionhome
chmod a+rwx $sessionhome
mkdir -p $datahome
chmod a+rwx $datahome
mkdir -p $htmlhome
chmod a+rwx $htmlhome

# Make sure the UVD html directory cannot be listed.
cp html/no_list.html $htmlhome/index.html

# Link the help files into the uvd directory.
pushd $htmlhome
ln -s ../help* .
ln -s ../*.jpg .
ln -s ../*.gif .
ln -s ../*.txt .
popd

#-----------------------------------------------------------

# Make the directory into which the data will actually be uploaded,
# and link it into the CGI directory
mkdir -p $uploadhome
chmod a+rwx $uploadhome

# Make sure the upload directory cannot be listed.
cp html/no_list.html $uploadhome/index.html

set uploadbase = `basename $uploadhome`
set uploadlink = $cgihome/$uploadbase
if (! -e $uploadlink) then
  ln -s $uploadhome $cgihome
endif
