#! /s/std/bin/perl

#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1999
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

#  This is a script to check whether the jspop is running, and restart
#  it if it's not.

############################################################

#  $Id$

#  $Log$
#  Revision 1.1  1999/12/10 20:15:21  wenger
#  Improved scripts now check separately for "regular" and "soil science"
#  jspop and deviseds.
#

############################################################

$foundJspop = 0;
$foundDevised = 0;

# One of the hardest parts of getting this script to work has been running
# ps in such a way that the port arguments still show up when the damn
# path to java gets real long.  -ww option to ps would guarantee that
# the line would be long enough, except that with the latest Intel/Solaris
# ps, this makes the command totally hang!!  RKW 1999-12-17.

# (We need to see the port arguments here so we can differentiate between
# the "regular" jspop and deviseds, and the "soil science" jspop and
# deviseds.)

$ps_cmd = "/usr/ucb/ps -axw";


open PS, "$ps_cmd >& 1 |" or die "can't fork: $!";

while (<PS>) {
  if ($_ =~ /java *jspop.*port59/) {
    $foundJspop = 1;
  }
  # Wildcard here because -w option screws up ps output.
  if ($_ =~ /devised.*port 59/) {
    $foundDevised = 1;
  }
}

close PS;


if (!$foundJspop) {
  $curTime = localtime(time());
  print "No jspop process found (at $curTime)\n";
  print "Restarting jspop\n";

  # Make sure we kill off any stray deviseds.
  system("kill_devised2 59");

  KillJspop();
  SaveLogs();

  StartJspop();
} elsif (!$foundDevised) {
  $curTime = localtime(time());
  print "No devised process found (at $curTime)\n";
  print "Restarting jspop\n";

  # If there are no deviseds running, that probably means there are problems
  # with the jspop, so kill it and start over.
  KillJspop();
  SaveLogs();

  StartJspop();
}

#-----------------------------------------------------------

sub SaveLogs {
  $timestamp = time();
  print "Saving log files as jspop.out.$timestamp and devised.out.$timestamp\n";

  # Perl's rename() function doesn't seem to work!?!
  @args = ("mv", "jspop.out", "jspop.out.$timestamp");
  0xffff & system(@args) == 0 or print "Can't rename jspop.out ($?)\n";

  @args = ("mv", "devised.out", "devised.out.$timestamp");
  0xffff & system(@args) == 0 or print "Can't rename devised.out ($?)\n";
}

#-----------------------------------------------------------

sub KillJspop {
  open PS, "$ps_cmd >& 1 |" or die "can't fork: $!";

  while (<PS>) {
    if ($_ =~ /java *jspop.*port59/) {
      print "Killing $_";
      $foundJspop = 1;
      @words = split /  */, $_;
      $pid = @words[1];
      system("kill $pid");
    }
  }

  close PS;
}

#-----------------------------------------------------------

sub StartJspop {
  sleep 15;
  system("cp DEVise.jspop_soil DEVise.jspop");
  system("jspop -cmdport5966 -imgport5944 &");
}
