#! /bin/csh -f

############################################################

# $Id$

# Note: specific port number must NOT be specified in this script.

############################################################

unsetenv CLASSPATH
set javaexec = `cat bin2/java`
$javaexec -Xmx128M -cp .:Jmol.jar JavaScreen.js -cgiurl/cgi-bin/js.cgi $*
