#! /bin/csh -f

############################################################

# $Id$

# Note: specific port number must NOT be specified in this script.

############################################################

bin2/java JavaScreen.js -cgiurl/cgi-bin/js.cgi $*
