#! /bin/csh -f

############################################################

# $Id$

# Note: specific port number must NOT be specified in this script.

############################################################

unsetenv CLASSPATH
set javaexec = `which java`
$javaexec -Xmx128M -cp . JavaScreen.js -cgiurl/cgi-bin/devise/js.cgi -screensize700x500 $*
