#! /bin/csh -f

############################################################

# $Id$

############################################################

nohup /s/std/bin/Xvfb :1 -screen 0 1280x1024x8 &
setenv DISPLAY unix:1.0

\rm devised.out
\rm jspop.out
touch devised.out
touch jspop.out

nohup java jspop $* > jspop.out
setenv DISPLAY unix:0.0
