#! /bin/csh -f

############################################################

# Start the jss (JavaScreen Server).

# Note: specific port number must NOT be specified in this script.

#-----------------------------------------------------------

# $Id$

############################################################

set path = ( /s/java-1/bin $path )

nohup jss_savepid $* &
