#! /bin/csh -f
rm *.class
javac DEViseJSLoader.java
javac jsa.java
# splitting the jar files into two.
# jsa1.jar
jar cf jsa1.jar DEViseJSLoader.class jsa.class
rm DEViseJSLoader.class jsa.class

# jsa2.jar 
jar cf jsa2.jar *.class  *.gif
