#! /bin/csh -f

############################################################

# Define ports and log files for JavaScreen-related processes.

# Note: if port values are changed here, the appropriate html
# files must also be changed so that the client tries to connect
# to the correct ports.

#-----------------------------------------------------------

# $Id$

############################################################

if ($#argv > 1) then
  echo "Usage: ports+files [id_string]"
  echo "Output: <cmd_port> <pop_port> <jss_port> <pop_file> <jss_file> <devised_file>"
  exit
endif

set idStr = ""
if ($#argv == 1) then
  set idStr = $argv[1]
endif

# "Standard" values.  Note: these should correspond to the values in
# DEViseGlobals.java.
set cmdPort = 6666
set popPort = 7666
set jssPort = 7766
set pFile = "logs/jspop.out"
set sFile = "logs/jss.out"
set dFile = "logs/devised.out"

if ($idStr == "") then
  # Leave "standard" values alone.

else
  if ($idStr == "regular") then
    # Use "standard" port numbers.

  else if ($idStr == "soil") then
    set cmdPort = 6670
    set popPort = 7670
    set jssPort = 7770

  else if ($idStr == "test") then
    set cmdPort = 6667
    set popPort = 7667
    set jssPort = 7767

  # Not test2 so that we avoid having searches for "test" hit it.
  else if ($idStr == "tst2") then
    set cmdPort = 6668
    set popPort = 7668
    set jssPort = 7768

  else if ($idStr == "wave") then
    set cmdPort = 6669
    set popPort = 7669
    set jssPort = 7769

  else
    #TEMP -- needs to go to stderr
    #echo "Warning: unrecognized ID string; using standard port numbers"

  endif

  set pFile = $pFile.$idStr
  set sFile = $sFile.$idStr
  set dFile = $dFile.$idStr
endif

echo "$cmdPort $popPort $jssPort $pFile $sFile $dFile"
