#! /bin/csh -f

############################################################

# This file is just to be able to run top from cron, and
# get the output, since the current Intel/Solaris crond
# is so messed up.

# $Id$

############################################################

set outfile = /tmp/top.out

if (-e $outfile) then
    rm $outfile
endif

/s/std/bin/top >& $outfile

# All this garbage because Sun's current crond on Intel/Solaris won't
# send mail correctly.
if (-e $outfile && ! -z $outfile) then
    cat $outfile | /usr/ucb/mail -s "top from cron" `whoami`
endif
