#! /bin/csh -f

#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 2000-2008
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

#  This script sets up this directory to run the JavaScreen (by making
#  appropriate links).

############################################################

#  $Id$

############################################################

#TEMP -- move this to a Makefile
# have a Makefile.config

if (! -e bin) then
  mkdir -p bin
endif 

if (-e bin/devised) then
  rm bin/devised
endif

cd bin
#TEMP -- get rid of hard-coded linux_rhel6
ln -s ../../../linux_rhel6/generic/devised .
if (! -e Tasvir) then
  ln -s /p/devise/public/bin/Tasvir .
endif
cd ..

if (! -e lib) then
  mkdir -p lib
endif 

if (! -e lib/composite.ini) then
  cd lib
  ln -s ../../../lib/composite.ini .
  cd ..
endif

if (! -e JavaScreen) then
  mkdir -p JavaScreen
endif
cd JavaScreen
ln -s ../*.gif .
ln -s ../resources .
ln -s ../html .
if (! -e UI) then
  mkdir -p UI
endif
cd UI
ln -s ../../UI/*.java .
cd ../..

cd html
ln -s ../resources/toolbar_icons/*.default.* .
cd ..
