#! /bin/csh -f
 
# Start a collaboration leader
./js -collableadernamecollab -collableaderpasspasswd -autoplayback -clientlogclient_log.1 -playbackoriginal -screensize600x400 &

sleep 10
 
# Start a collaboration follower (we're not using the normal js script
# here so we can get the follower's PID)
set javaexec = `cat bin2/java`
$javaexec JavaScreen.js -collabnamecollab -collabpasspasswd -screensize600x400 &
set follower_id = $!

sleep 180

# Kill the follower
kill -9 $follower_id

# Check whether the leader process still alive
set js = `ps | grep js$`
if ("$js" != "") then
    echo "\nError found with JavaScreen. Please check logs."
    set success = 0
endif
