BEGINMENU(File)
MENUITEM New 
CHECKMENUITEM Open OpenMe
MENUITEM SEPARATOR
MENUITEM Close
ENDMENU

BEGINMENU(View)
MENUITEM New 
CHECKMENUITEM Delete DeleteMe
BEGINMENU(Cascade)
MENUITEM C1 OnFileNew
BEGINMENU(Deeper)
MENUITEM D1 OnFileClose
MENUITEM D2 OnFileNew
ENDMENU
MENUITEM C2 
ENDMENU
ENDMENU

BEGINPOPUPMENU(PopupTest)
MENUITEM New 
CHECKMENUITEM Open OpenMe
MENUITEM SEPARATOR
MENUITEM Close
BEGINPOPUPMENU(Cascade)
MENUITEM C1 OnFileNew
BEGINPOPUPMENU(Deeper)
MENUITEM D1 OnFileClose
MENUITEM D2 OnFileNew
ENDMENU
MENUITEM C2 
ENDMENU
ENDMENU

