#! /bin/sh -f

# Tests chem shift reference processing (special version that simulates
# what chemShift on leech does).

result=0

rm -f data_dir/csr.run >& /dev/null
rm -f data_dir/vis_server/csr.run >& /dev/null

tests/test6_main &

tests/dummy_csr_server -exit -time_limit 60

wait $!
result=$? 
exit $result
