#! /bin/csh -f

# Tests that -peakonly doesn't do anything when file already has
# peak list data in proper tags.

set result = 0

rm -r -f */18777*

echo -n "Processing NMR-STAR: "
./s2d -nomail -name 18777 -file test_data/bmr18777.str -force -check_res_list -check_pct -peakonly
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif
mv tmp/s2d.out tmp/test_peak6.out


source tests/test_peak6_check


echo -n "Test_peak6 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
