#! /bin/csh -f

# Tests BMRB 6792 -- caused an error during Hongyang's processing.

set result = 0

rm -r -f */6792*

echo -n "Processing NMR-STAR: "
./s2d -nomail -name 6792 -file test_data/bmr6792_3.str -force -check_res_list -check_pct -peakonly
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif
mv tmp/s2d.out tmp/test_peak23.out


source tests/test_peak23_check


echo -n "Test_peak23 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
