#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1992-1995
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  $Id$

#  $Log$
#  Revision 1.7  1995/09/28 15:10:07  jussi
#  Added copyright and CVS log messages.
#

############################################################

include ../Makefile.config

VPATH = ../../tape
include $(VPATH)/Makefile.base
include $(VPATH)/Makefile.sun
