#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1992-1996
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  $Id$

#  $Log$
#  Revision 1.3  1996/05/20 18:37:57  jussi
#  Replaced PENTIUM flag with SOLARIS.
#
#  Revision 1.2  1996/02/13 16:44:16  jussi
#  Replaced /usr/X11R6/include with /s/X11/include.
#
#  Revision 1.1  1995/11/09 18:52:59  jussi
#  Initial revision.

############################################################

ARCH_FLAGS = -DSGI -I/s/X11/include -I/usr/freeware/include -I/usr/freeware/src/perl5.002

VPATH = ../../crsp
include $(VPATH)/Makefile.base
include $(VPATH)/Makefile.sgi
