BEGINMENU(File)
MENUITEM New
MENUITEM Close
ENDMENU

BEGINMENU(Draw)
BEGINMENU(View) 
MENUITEM Single 
CHECKMENUITEM Multiple
ENDMENU
MENUITEM Copy
MENUITEM Delete
MENUITEM SEPARATOR
MENUITEM Group
MENUITEM Ungroup
MENUITEM SEPARATOR
MENUITEM Refresh
MENUITEM Clear
ENDMENU

BEGINMENU(Edit)
BEGINMENU(Align)
MENUITEM Left    
MENUITEM Right  
MENUITEM Top
MENUITEM Bottom
ENDMENU
BEGINMENU(Equalize)
MENUITEM Width
MENUITEM Height
ENDMENU
BEGINMENU(Distribute)
MENUITEM Horizontally
MENUITEM Vertically
ENDMENU
BEGINMENU(Edges)
MENUITEM Align  
MENUITEM Rivet 
MENUITEM UnRivet
ENDMENU
ENDMENU
