/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Environment */

#ifndef _Included_Environment
#define _Included_Environment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Environment
 * Method:    getSystemEnv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Environment_getSystemEnv
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
