#! /bin/csh -f

############################################################

# Script to run automatic ASOS data update.

# $Id$

############################################################

set outfile = /tmp/asos_update.out

if (-e $outfile) then
    rm $outfile
endif

/s/std/bin/runauth ./asos_datafile.pl >& $outfile

# All this garbage because Sun's current crond on Intel/Solaris won't
# send mail correctly.
if (-e $outfile && ! -z $outfile) then
    /s/std/bin/cat $outfile | /usr/ucb/mail -s "ASOS update from cron" `/s/std/bin/whoami`
endif
