#! /bin/csh -f
############################################################

# Run the standard DEVise with the user's own data, sessions, etc.

# $Id$

############################################################

# limit coredumpsize 0
limit descriptors 256

set dir = `dirname $0`

setenv DEVISE_PROG	`$dir/devise_prog`
set devise_run = $DEVISE_PROG/run

source $devise_run/dev_prog.gen
setenv DEVISE_VIS `dirname $0`/..
source $devise_run/dev_vis.gen

source $devise_run/start_mono
