#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1998-2005
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  This Makefile has settings that apply to everything compiled
#  on the AMD 64/Linux architecture.

############################################################

#  $Id$

#  $Log$
#  Revision 1.1.2.1  2005/10/20 18:14:21  wenger
#  More cleanup to Tao and SPARC/Solaris, added stuff for some
#  more of the linuxes.
#

############################################################

CC = g++ 
C  = gcc 

TCL_TK_DIR = /usr
TCL_TK_INCLUDE = -I$(TCL_TK_DIR)/include
TCL_TK_LIBDIR = -L$(TCL_TK_DIR)/lib64
TCL_TK_LIBS = -ltk8.4 -ltcl8.4

XLIB_DIR = /usr/X11R6
XLIB_INCLUDE = -I$(XLIB_DIR)/include
XLIB_LIBDIR = -L$(XLIB_DIR)/lib64

ARCH_FLAGS = -DLINUX $(XLIB_INCLUDE) $(TCL_TK_INCLUDE)
ARCH_FLAGS += -DSBM_PROCESS -DSBM_SHARED_MEMORY
ARCH_FLAGS += -Wno-deprecated

ARCH_ENDIAN =
