#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1992-1995
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  $Id$

#  $Log$
#  Revision 1.1  1997/08/11 14:16:08  wenger
#  Modifications to get DEVise to compile on Linux.
#

############################################################

PERL_CORE = /usr/lib/perl5/i486-linux/5.003/CORE

ARCH_FLAGS   = -DLINUX
ARCH_LDFLAGS =
ARCH_LDPOST  =

VPATH = ../../unidata
include ../../unidata/Makefile.base
include ../../unidata/Makefile.linux
