#! /bin/csh -f
# Generate visualizations for dynamics movies.

./s2d -bmrbid 15451 -name 15451_dyn_movie \
  -s2p_url http://www.bmrb.wisc.edu/ftp/pub/bmrb/derived_data/s2predict/ \
  -s2p_name 15451 -do_s2p 2 -do_dyn_movie 1 -force -dyn_movie_demo
mv tmp/s2d.out tmp/15451_movie.s2d.out

./s2d -bmrbid 17306 -name 17306_dyn_movie \
  -s2p_url http://www.bmrb.wisc.edu/ftp/pub/bmrb/derived_data/s2predict/ \
  -s2p_name 17306 -do_s2p 2 -do_dyn_movie 1 -force -dyn_movie_demo
mv tmp/s2d.out tmp/17306_movie.s2d.out

./s2d -bmrbid 5154 -name 5154_dyn_movie \
  -s2p_url http://www.bmrb.wisc.edu/ftp/pub/bmrb/derived_data/s2predict/ \
  -s2p_name 5154 -do_s2p 2 -do_dyn_movie 1 -force -dyn_movie_demo
mv tmp/s2d.out tmp/5154_movie.s2d.out

./s2d -bmrbid 5550 -name 5550_dyn_movie \
  -s2p_url http://www.bmrb.wisc.edu/ftp/pub/bmrb/derived_data/s2predict/ \
  -s2p_name 5550 -do_s2p 2 -do_dyn_movie 1 -force -dyn_movie_demo
mv tmp/s2d.out tmp/5550_movie.s2d.out

./s2d -bmrbid 4267 -name 4267_dyn_movie \
  -s2p_url http://www.bmrb.wisc.edu/ftp/pub/bmrb/derived_data/s2predict/ \
  -s2p_name 4267 -do_s2p 2 -do_dyn_movie 1 -force -dyn_movie_demo
mv tmp/s2d.out tmp/4267_movie.s2d.out

./s2d -bmrbid 15562 -name 15562_dyn_movie \
  -s2p_url http://www.bmrb.wisc.edu/ftp/pub/bmrb/derived_data/s2predict/ \
  -s2p_name 15562 -do_s2p 2 -do_dyn_movie 1 -force -dyn_movie_demo
mv tmp/s2d.out tmp/15562_movie.s2d.out
