#!/bin/csh -f

set path = ($path /s/std/bin)
# For yola.bmrb.wisc.edu
set path = ($path /usr/java/bin)

limit filesize 1000
# We need a big cpu time limit for 4096.
limit cputime 1000
limit coredumpsize 0

unsetenv LD_LIBRARY_PATH

/bin/rm -f s2d.out
/bin/rm -f error.log

setenv CLASSPATH ./java_classes:./java_classes/starlibj.jar
java S2DMain $* data_dir session_dir >& s2d.out
