#! /bin/csh -f

limit filesize 1000
# We need a big cpu time limit for 4096.
limit cputime 1000
limit coredumpsize 0

unsetenv LD_LIBRARY_PATH

rm -f s2d.out
rm -f error.log

setenv CLASSPATH ./java_classes:./java_classes/starlibj.jar
bin/java S2DMain $* data_dir session_dir >& s2d.out
chmod 644 s2d.out
