#! /bin/csh -f
# "Upload and visualize data" conversion.

limit filesize 30000
# We need a big cpu time limit for 4096.
limit cputime 1000
limit coredumpsize 0

unsetenv LD_LIBRARY_PATH

set outfile = tmp/uvd.out
rm -f $outfile

set path = ($path .)
bin/java -Xmx512m -classpath ./s2d.jar -mx50000000 star2devise.S2DMain \
  -data_dir data_dir/uvd -js_data_dir bmrb/dynamic_data/uvd \
  -session_dir session_dir/.uvd -html_dir html_dir/uvd \
  -conn_file chem_info/connections -no_protein_check -uvd $* >& $outfile
set failed = $status
chmod 644 $outfile
if ($failed) then
  echo FAILED
  exit 1
else
  echo OK
endif
