#! /bin/csh -f

# $Id$

# Copy dynamic libraries for Solaris/SPARC.

if (! -e dyn_lib) then
  mkdir dyn_lib
endif

# On anor, 2005-10-20.
cp /s/tcl/lib/libtk8.3.so dyn_lib
cp /s/tcl/lib/libtcl8.3.so dyn_lib
cp /s/X11R6/lib/libX11.so.6.2 dyn_lib
cp /usr/lib/libsocket.so.1 dyn_lib
cp /usr/lib/libnsl.so.1 dyn_lib
cp /s/gcc-2.95.3/sun4x_58/lib/libstdc++.so.2.10.0 dyn_lib
cp /usr/lib/libm.so.1 dyn_lib
cp /usr/lib/libc.so.1 dyn_lib
cp /usr/lib/libdl.so.1 dyn_lib
cp /usr/lib/libmp.so.2 dyn_lib
cp /usr/platform/SUNW,Sun-Blade-1000/lib/libc_psr.so.1 dyn_lib

# This is necessary to get things to work right at the Osaka BMRB mirror.
cp /usr/lib/nss_files.so.1 dyn_lib

chmod 644 dyn_lib/*.so*
