ARCH_FLAGS = -DPENTIUM -I/usr/X11R6/include -I../tcl/include
ARCH_LDFLAGS = -L /usr/X11R6/lib -L ../tcl/lib -R /usr/X11R6/lib 

VPATH = ../../ams
include $(VPATH)/Makefile.base

depend:
	makedepend -I../../graphics -I../../graphics.new \
		-I../../tape -I/usr/X11R6/include -I../tcl/include \
		$(VPATH)/*.c

# DO NOT DELETE THIS LINE -- make depend depends on it.

../../ams/MapClassInfo.o: /usr/include/sys/time.h
../../ams/MapClassInfo.o: /usr/include/sys/feature_tests.h
../../ams/MapClassInfo.o: /usr/include/sys/types.h
../../ams/MapClassInfo.o: /usr/include/sys/isa_defs.h
../../ams/MapClassInfo.o: /usr/include/sys/machtypes.h
../../ams/MapClassInfo.o: /usr/include/sys/select.h /usr/include/sys/time.h
../../ams/MapClassInfo.o: /usr/include/math.h ../tcl/include/tcl.h
../../ams/MapClassInfo.o: /usr/include/stdio.h ../../graphics/DeviseTypes.h
../../ams/MapClassInfo.o: ../../graphics/Display.h ../../graphics/Geom.h
../../ams/MapClassInfo.o: ../../graphics/Dispatcher.h ../../graphics/DList.h
../../ams/MapClassInfo.o: ../../graphics/Exit.h ../../graphics/VisualArg.h
../../ams/MapClassInfo.o: ../../graphics/Color.h ../../graphics/Journal.h
../../ams/MapClassInfo.o: ../../graphics/ColorMgr.h
../../ams/MapClassInfo.o: ../../graphics.new/RectShape.h
../../ams/MapClassInfo.o: ../../graphics/Transform.h
../../ams/MapClassInfo.o: ../../graphics/WindowRep.h ../../graphics/Pattern.h
../../ams/MapClassInfo.o: ../../graphics/DevisePixmap.h
../../ams/MapClassInfo.o: ../../graphics/Compress.h
../../ams/MapClassInfo.o: ../../graphics.new/Shape.h ../../graphics/Control.h
../../ams/MapClassInfo.o: ../../graphics.new/TDataCMap.h
../../ams/MapClassInfo.o: ../../graphics.new/ConnectorShape.h
../../ams/MapClassInfo.o: ../../graphics.new/Connector.h
../../ams/MapClassInfo.o: ../../graphics.new/ShapeID.h
../../ams/MapClassInfo.o: ../../graphics.new/GDataBin.h
../../ams/MapClassInfo.o: ../../graphics.new/RecId.h
../../ams/MapClassInfo.o: ../../graphics.new/ActionDefault.h
../../ams/MapClassInfo.o: ../../graphics/Action.h ../../graphics/Util.h
../../ams/MapClassInfo.o: /usr/include/assert.h /usr/include/stdlib.h
../../ams/MapClassInfo.o: /usr/include/ctype.h ../../graphics/Selection.h
../../ams/MapClassInfo.o: ../../graphics/View.h ../../graphics/ViewWin.h
../../ams/MapClassInfo.o: ../../graphics/ViewCallback.h
../../ams/MapClassInfo.o: ../../graphics/AttrList.h ../../graphics/Config.h
../../ams/MapClassInfo.o: ../../graphics/Cursor.h ../../graphics/Init.h
../../ams/MapClassInfo.o: ../../graphics/BufPolicy.h
../../ams/MapClassInfo.o: ../../graphics.new/TDataMapDispatch.h
../../ams/MapClassInfo.o: ../../graphics.new/TDataMap.h
../../ams/MapClassInfo.o: ../../graphics.new/Bitmap.h
../../ams/MapClassInfo.o: ../../graphics.new/GDataRec.h
../../ams/MapClassInfo.o: ../../graphics.new/DispQueryProc.h
../../ams/MapClassInfo.o: ../../graphics.new/QueryProcSimple.h
../../ams/MapClassInfo.o: ../../graphics.new/QueryProc.h
../../ams/MapClassInfo.o: ../../graphics.new/BufHint.h
../../ams/MapClassInfo.o: ../../graphics.new/QueryProcFull.h
../../ams/MapClassInfo.o: ../../graphics.new/QPRange.h
../../ams/MapClassInfo.o: ../../graphics.new/BufMgr.h
../../ams/MapClassInfo.o: ../../graphics.new/BufferPolicy.h
../../ams/MapClassInfo.o: ../../graphics.new/RecOrder.h
../../ams/MapClassInfo.o: ../../graphics.new/Temp.h
../../ams/MapClassInfo.o: ../../graphics/ViewWinVer.h
../../ams/MapClassInfo.o: ../../graphics.new/Snapshot.h
../../ams/MapClassInfo.o: ../../graphics.new/ViewScatter.h
../../ams/MapClassInfo.o: ../../graphics.new/ViewGraph.h
../../ams/MapClassInfo.o: ../../ams/MapClassInfo.h ../../graphics/ClassDir.h
../../ams/MapClassInfo.o: ../../ams/Soil.h ../../ams/AmsMap.h
../../ams/ams.o: /usr/include/sys/types.h /usr/include/sys/feature_tests.h
../../ams/ams.o: /usr/include/sys/isa_defs.h /usr/include/sys/machtypes.h
../../ams/ams.o: /usr/include/sys/select.h /usr/include/sys/time.h
../../ams/ams.o: /usr/include/sys/time.h /usr/include/stdio.h
../../ams/ams.o: ../../graphics/DeviseTypes.h ../../graphics/Dispatcher.h
../../ams/ams.o: ../../graphics/DList.h ../../graphics/Exit.h
../../ams/ams.o: ../../graphics/VisualArg.h ../../graphics/Color.h
../../ams/ams.o: ../../graphics/Journal.h ../../graphics/Display.h
../../ams/ams.o: ../../graphics/Geom.h /usr/include/math.h
../../ams/ams.o: ../../graphics/ColorMgr.h ../../graphics/Control.h
../../ams/ams.o: ../../graphics/Init.h ../../graphics/BufPolicy.h
../../ams/ams.o: ../../graphics/WinClassInfo.h ../../graphics/ClassDir.h
../../ams/ams.o: ../../graphics.new/MapInterpClassInfo.h
../../ams/ams.o: ../../graphics/VisualLinkClassInfo.h ../../graphics/View.h
../../ams/ams.o: ../../graphics/ViewWin.h ../../graphics/WindowRep.h
../../ams/ams.o: ../../graphics/Transform.h ../../graphics/Pattern.h
../../ams/ams.o: ../../graphics/DevisePixmap.h ../../graphics/Compress.h
../../ams/ams.o: ../../graphics/ViewCallback.h ../../graphics/AttrList.h
../../ams/ams.o: ../../graphics/Config.h ../../graphics/Cursor.h
../../ams/ams.o: ../../graphics/AxisLabelClassInfo.h
../../ams/ams.o: ../../graphics.new/ViewClassInfo.h
../../ams/ams.o: ../../graphics.new/CompositeParser.h
../../ams/ams.o: ../../graphics.new/RecInterp.h
../../ams/ams.o: ../../graphics.new/QueryProc.h ../../graphics.new/RecId.h
../../ams/ams.o: ../../tape/QueryProcTape.h ../../graphics.new/QPRange.h
../../ams/ams.o: ../../tape/SortedTable.h /usr/include/assert.h
../../ams/ams.o: ../../graphics.new/GData.h ../../graphics.new/TData.h
../../ams/ams.o: ../../graphics.new/RecOrder.h ../../graphics.new/BufMgr.h
../../ams/ams.o: ../../graphics.new/BufHint.h
../../ams/ams.o: ../../graphics.new/BufferPolicy.h
../../ams/ams.o: ../../graphics.new/ViewGraph.h ../../graphics.new/TDataMap.h
../../ams/ams.o: ../../graphics.new/ShapeID.h ../../graphics.new/Bitmap.h
../../ams/ams.o: ../../graphics.new/GDataRec.h
../../ams/ams.o: ../../graphics/CursorClassInfo.h
../../ams/ams.o: ../../tape/TDataTapeInterp.h ../../tape/TDataTape.h
../../ams/ams.o: ../../tape/tapedrive.h ../../tape/machdep.h
../../ams/ams.o: /usr/include/limits.h /usr/include/sys/param.h
../../ams/ams.o: /usr/include/sys/unistd.h /usr/include/sys/ioctl.h
../../ams/ams.o: /usr/include/sys/wait.h /usr/include/sys/siginfo.h
../../ams/ams.o: /usr/include/sys/machsig.h /usr/include/vm/faultcode.h
../../ams/ams.o: /usr/include/sys/procset.h /usr/include/sys/ipc.h
../../ams/ams.o: /usr/include/sys/shm.h /usr/include/sys/sem.h
../../ams/ams.o: ../../graphics/ParseCat.h ../../graphics.new/Command.h
../../ams/ams.o: ../../graphics/Timer.h ../../ams/MapClassInfo.h
../../ams/amsStat.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
../../ams/amsStat.o: /usr/include/sys/types.h /usr/include/sys/isa_defs.h
../../ams/amsStat.o: /usr/include/sys/machtypes.h /usr/include/sys/select.h
../../ams/amsStat.o: /usr/include/sys/time.h /usr/include/sys/time.h
../../ams/amsStat.o: /usr/include/sys/stat.h /usr/include/fcntl.h
../../ams/amsStat.o: /usr/include/sys/fcntl.h /usr/include/limits.h
../../ams/amsStat.o: /usr/include/sys/uio.h /usr/include/unistd.h
../../ams/amsStat.o: /usr/include/sys/unistd.h
../../ams/amsStat.o: ../../graphics.new/TDataAppend.h
../../ams/amsStat.o: ../../graphics.new/TData.h ../../graphics/DeviseTypes.h
../../ams/amsStat.o: ../../graphics.new/RecId.h ../../graphics.new/RecOrder.h
../../ams/amsStat.o: ../../graphics/VisualArg.h ../../graphics/Color.h
../../ams/amsStat.o: ../../graphics/DList.h ../../graphics/Exit.h
../../ams/amsStat.o: ../../graphics.new/DiskFile.h ../../graphics.new/ams.h
../../ams/amsStat.o: /usr/include/math.h
../../ams/extendAms.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
../../ams/extendAms.o: /usr/include/sys/types.h /usr/include/sys/isa_defs.h
../../ams/extendAms.o: /usr/include/sys/machtypes.h /usr/include/sys/select.h
../../ams/extendAms.o: /usr/include/sys/time.h /usr/include/sys/time.h
../../ams/extendAms.o: /usr/include/sys/stat.h /usr/include/fcntl.h
../../ams/extendAms.o: /usr/include/sys/fcntl.h /usr/include/limits.h
../../ams/extendAms.o: /usr/include/sys/uio.h /usr/include/unistd.h
../../ams/extendAms.o: /usr/include/sys/unistd.h ../../graphics.new/ams.h
../../ams/extendAms.o: /usr/include/math.h
../../ams/testdir.o: /usr/include/stdio.h /usr/include/sys/feature_tests.h
../../ams/testdir.o: /usr/include/sys/types.h /usr/include/sys/isa_defs.h
../../ams/testdir.o: /usr/include/sys/machtypes.h /usr/include/sys/select.h
../../ams/testdir.o: /usr/include/sys/time.h /usr/include/sys/time.h
