CC = g++

CFLAGS = $(ARCH_FLAGS) -O -Wall -I../../graphics.new
LDFLAGS = $(ARCH_LDFLAGS) $(ARCH_LDPOST)

.C.o:
	$(CC) -c $(CFLAGS) $<

SRC = http_url.c atof.C

OBJ = http_url.o atof.o

all: http_url atof

http_url: http_url.o
	$(CC) -o $@ $@.o $(LDFLAGS)

atof: atof.o
	$(CC) -o $@ $@.o $(LDFLAGS)

.PHONY: clean mostlyclean

clean: mostlyclean
	-rm http_url

mostlyclean:
	-rm $(OBJ)
