#! /bin/csh -f
# Visualization server conversion.
# Note: I don't think this is actually used anymore on the BMRB web site.
#   This may be the the script that was used by Jafar.  wenger 2008-07-08

limit filesize 30000
# We need a big cpu time limit for 4096.
limit cputime 1000
limit coredumpsize 0

unsetenv LD_LIBRARY_PATH

set outfile = tmp/vsc.out
rm -f $outfile

set path = ($path .)
bin/java -classpath ./s2d.jar star2devise.S2DMain \
  -data_dir data_dir/vis_server -js_data_dir bmrb/dynamic_data/vis_server \
  -session_dir session_dir/vis_server -html_dir html_dir \
  -conn_file chem_info/connections -no_protein_check -do_pdb 2 $* >& $outfile
set failed = $status
chmod 666 $outfile
if ($failed) then
  echo FAILED
  exit 1
else
  echo OK
endif
