
#
# Solaris
#
ARCH_FLAGS = -DSolaris
DEBUG_FLAG = -gstabs
TCL_INCS = -I/s/tcl/include
TCL_LIBS = -L/s/tcl/lib -R/s/tcl/lib -ltk8.3 -ltcl8.3
X_INCS = -I/s/X11/include
X_LIBS = -L/s/X11/lib -R/s/X11/lib -lX11 -lXmu
SOCKET_LIBS = -lsocket -lnsl

include Makefile.base
