depend:
	makedepend -fMakefile.aix -I../graphics -I../graphics.new \
		-I../tape -I../issm -I../crsp -I../compustat *.c *.C

# DO NOT DELETE THIS LINE -- make depend depends on it.

tapedrive: tapedrive.h ../graphics.new/machdep.h ../graphics.new/DCE.h
tapedrive: ../graphics/Exit.h ../graphics/DevError.h
tapedrive: ../graphics/DeviseTypes.h ../graphics/DevStatus.h
testtape: tapedrive.h ../graphics.new/machdep.h
vertape: tapedrive.h ../graphics.new/machdep.h
