CC = g++
CPPFLAGS = $(ARCH_FLAGS) -O -I../../graphics.new -I../../tape \
	-Wall -Wno-unused -fexternal-templates

LIBSRC = compustat.c

LIBOBJ = compustat.o

TESTSRC = index.c extract.c

ALLSRC= $(LIBSRC) $(TESTSRC) 

LIBOBJS= $(LIBOBJ)

cstatobj.o: $(LIBOBJS)
	ld -r -o $@ $(LIBOBJS)

index:	index.o
	$(CC) $(CPPFLAGS) -o $@ $@.o ../tape/tapedrive.o

extract:	extract.o $(LIBOBJS)
	$(CC) $(CPPFLAGS) -o $@ $@.o $(LIBOBJS) ../tape/tapedrive.o
