#include "RelationManager.h"
#include "types.h"
#include "Interface.h"
#include "Utility.h"
#include "sysdep.h"


RelationManager::RelationManager()
{
	string idFile = DTE_ENV_VARS.valueOf(DTE_ENV_VARS.idFile);
	string definitionFile = DTE_ENV_VARS.valueOf(DTE_ENV_VARS.definitionFile);
        //cerr << "using id file: " << idFile << endl;
        //cerr << "using definition file: " << definitionFile << endl;
	if(idFile.empty()){
		err = "Please set up the environment variable \'" +
			DTE_ENV_VARS.idFile + 
			"\' to point to an empty file" +
			" or a file that contains table id entries.";
		goto end;
	}
	if(definitionFile.empty()){
		err = "Please set up the environment variable \'" +
			DTE_ENV_VARS.definitionFile + 
			"\' to point to an empty file" +
			" or a file that contains table definition entries.";
		goto end;
	}
#if 0
  cerr << "HERE HERE4\n";
	if(!fileExists(idFile)){
		string err = "Could not open file: " + idFile + " pointed by " +
			" env var " + DTE_ENV_VARS.idFile;
		goto end;
	}

  cerr << "HERE HERE5\n";
	if(!fileExists(definitionFile)){
		string err = "Could not open file: " + definitionFile 
			+ " pointed by " +
			" env var " + DTE_ENV_VARS.definitionFile;
		goto end;
	}
#endif

	idStream.open(idFile.c_str(), ios::in | ios::out);
	if (!idStream.good()) {
		cout << "Error: open of " << idFile.c_str() << " failed.\n";
		perror("open");
		assert(0);
	}

	defStream.open(definitionFile.c_str(),  ios::in | ios::out);
	if (!defStream.good()) {
		cout << "Error: open of " << definitionFile.c_str() << " failed.\n";
		perror("open");
		assert(0);
	}

	end:;
}

RelationId RelationManager::registerNewRelation(const Interface& myInterface)
{
	if(!err.empty()){
		THROW(new Exception(err), RelationId());
	}
	int nextId = 0;
	idStream.seekp(0);
        assert(idStream.good());
	if(!idStream.read((char*)&nextId, sizeof(int))){
		
		// file is empty, initialize it

		idStream.clear();
                assert(idStream.good());
		int futureId = htonl(3);	// next id to be created
		idStream.write((char*)&futureId, sizeof(int));
                assert(idStream.good());
		futureId = htonl(0);	// offset, for future use
		idStream.write((char*)&futureId, sizeof(int));
		assert(idStream.good());
		nextId = 2;
		defStream << "DO NOT EDIT THIS FILE\n" << endl;
	}
	else{
		nextId = ntohl(nextId);
		int futureId = htonl(nextId + 1);	// next id to be created
		assert(idStream.seekp(0));
		idStream.write((char*)&futureId, sizeof(int));
		assert(idStream.good());
	}
	defStream.seekp(0, ios::end);
	int nextPos = htonl(defStream.tellp());	// this id points to offset 0
	idStream.seekp(0, ios::end);
	idStream.write((char*)&nextPos, sizeof(int));
        idStream.flush();       // kb: I added, but not really needed

	myInterface.write(defStream);
	defStream << endl;

	return RelationId(DTE_SERVER_ID, nextId);
}

Interface* RelationManager::createInterface(const RelationId& relId)
{
	if(!err.empty()){
                cerr << "had an error! " << err<< endl;
		THROW(new Exception(err), 0);
	}
	assert(relId.getServerId() == DTE_SERVER_ID || !"not implemented");
	
	int idOffset = relId.getLocalId();
        cerr << "got idOffset: " << idOffset << endl;

	idStream.seekg(idOffset * sizeof(int));
	
	int defOffset;
	if(!idStream.read((char*)&defOffset, sizeof(int))){
		
		// illegal relation id

		idStream.clear();
		string msg = "No local relation with relation id: " +
			relId.toString() + " exists";
                cerr << msg << endl;
		THROW(new Exception(msg), 0);
	}
	defOffset = ntohl(defOffset);
        cerr << "got defOffset: " << defOffset << endl;

	defStream.seekg(defOffset);
	assert(defStream.good());

        //kb: how did I break this?? I added this to fix it
        Interface* interface = Interface::create(defStream);
	assert(interface);
	assert(defStream.good());

        // StandardInterface* interface = new StandardInterface();
        // TRY(interface->read(defStream), NULL);
	return interface;
}

void RelationManager::deleteRelation(const RelationId&)
{
	// mark relation deleted
}
