#include "RelationManager.h"
#include "types.h"
#include "Interface.h"

#include "sysdep.h"

RelationManager::RelationManager()
{
	string idFile = DTE_ENV_VARS.valueOf(DTE_ENV_VARS.idFile);
	string definitionFile = DTE_ENV_VARS.valueOf(DTE_ENV_VARS.definitionFile);
	if(idFile.empty()){
		err = "Please set up the environment variable \'" +
			DTE_ENV_VARS.idFile + 
			"\' to point to an empty file" +
			" or a file that contains table id entries.";
		goto end;
	}
	if(definitionFile.empty()){
		err = "Please set up the environment variable \'" +
			DTE_ENV_VARS.definitionFile + 
			"\' to point to an empty file" +
			" or a file that contains table definition entries.";
		goto end;
	}

	if(!fileExists(idFile)){
		string err = "Could not open file: " + idFile + " pointed by " +
			" env var " + DTE_ENV_VARS.idFile;
		goto end;
	}

	if(!fileExists(definitionFile)){
		string err = "Could not open file: " + definitionFile 
			+ " pointed by " +
			" env var " + DTE_ENV_VARS.definitionFile;
		goto end;
	}

	idStream.open(idFile.c_str(), ios::in | ios::out);
	assert(idStream);

	defStream.open(definitionFile.c_str(),  ios::in | ios::out);
	assert(defStream);

	end:;
}

RelationId RelationManager::registerNewRelation(const Interface& interface)
{
	if(!err.empty()){
		THROW(new Exception(err), RelationId());
	}
	int nextId = 0;
	idStream.seekp(0);
	if(!idStream.read(&nextId, sizeof(int))){
		
		// file is empty, initialize it

		idStream.clear();
		int futureId = htonl(3);	// next id to be created
		idStream.write(&futureId, sizeof(int));
		futureId = htonl(0);	// offset, for future use
		idStream.write(&futureId, sizeof(int));
		assert(idStream);
		nextId = 2;
		defStream << "DO NOT EDIT THIS FILE\n" << endl;
	}
	else{
		nextId = ntohl(nextId);
		int futureId = htonl(nextId + 1);	// next id to be created
		assert(idStream.seekg(0));
		idStream.write(&futureId, sizeof(int));
		assert(idStream);
	}
	defStream.seekg(0, ios::end);
	int nextPos = htonl(defStream.tellg());	// this id points to offset 0
	idStream.seekg(0, ios::end);
	idStream.write(&nextPos, sizeof(int));

	interface.write(defStream);
	defStream << endl;

	return RelationId(DTE_SERVER_ID, nextId);
}

Interface* RelationManager::createInterface(const RelationId& relId)
{
	if(!err.empty()){
		THROW(new Exception(err), 0);
	}
	assert(relId.getServerId() == DTE_SERVER_ID || !"not implemented");
	
	int idOffset = relId.getLocalId();

	idStream.seekp(idOffset * sizeof(int));
	
	int defOffset;
	if(!idStream.read(&defOffset, sizeof(int))){
		
		// illegal relation id

		idStream.clear();
		string msg = "No local relation with relation id: " +
			relId.toString() + " exists";
		THROW(new Exception(msg), 0);
	}
	defOffset = ntohl(defOffset);

	defStream.seekp(defOffset);
	assert(defStream);

	char* space = new char[INITIAL_INTERFACE_SIZE];
	void* retVal = (Interface*) new (space) StandardInterface();

	interfaceRead(defStream, retVal);

	assert(defStream);
	return (Interface*) retVal;
}

void RelationManager::deleteRelation(const RelationId&)
{
	// mark relation deleted
}
