#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1992-1995
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  $Id$

#  $Log$
#  Revision 1.1  1995/11/09 18:54:10  jussi
#  Initial revision.
#

############################################################

include ../Makefile.config

VPATH = ../../crsp
include $(VPATH)/Makefile.base
include $(VPATH)/Makefile.sun
