ARCH_FLAGS = -DPENTIUM -I/usr/X11R6/include
#CC = CC
VPATH = /p/miron/miron/DEVise/src/graphics
include /p/miron/miron/DEVise/src/graphics/Makefile.solaris
# DO NOT DELETE THIS LINE -- make depend depends on it.
