#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1992-1995
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  $Id$

#  $Log$
#  Revision 1.5  1995/09/28 15:12:01  jussi
#  Added copyright and CVS log messages.
#

############################################################

ARCH_FLAGS = -DPENTIUM -I/usr/X11R6/include -I/s/tcl/include

VPATH = ../../graphics
include $(VPATH)/Makefile.base
include $(VPATH)/Makefile.solaris
