#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1992-1996
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  $Id$

#  $Log$
#  Revision 1.6  1998/02/26 17:20:26  wenger
#  Fixed problems with yesterday's commit.
#
#  Revision 1.4  1996/05/20 18:37:56  jussi
#  Replaced PENTIUM flag with SOLARIS.
#
#  Revision 1.3  1996/02/13 16:44:16  jussi
#  Replaced /usr/X11R6/include with /s/X11/include.
#

############################################################

include ../Makefile.config

VPATH = ../../compustat
include $(VPATH)/Makefile.base
include $(VPATH)/Makefile.solaris
