#! /bin/csh -f
############################################################

# Run standard DEVise (client/server form) with the standard
# data, sessions, etc.

# $Id$

############################################################

limit coredumpsize 0
limit descriptors 256

#TEMP -- get rid of hard-coded path eventually
set devise_run = /p/devise/release/run

source $devise_run/dev_prog.std
source $devise_run/dev_vis.std

source $devise_run/start_cs
