#! /bin/csh -f

#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 2002
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

#  Run this script *on pumori* to set up the linux-intel dynamic
#  libraries.

############################################################

#  $Id$

############################################################

# This is for RedHat 7.2.

cp /usr/lib/libtk.so.0 .
cp /usr/lib/libtcl.so.0 .
cp /usr/X11R6/lib/libX11.so.6 .
cp /lib/libdl.so.2 .
cp /s/gcc-2.95.3/i386_rh72/lib/libstdc++-libc6.2-2.so.3 .
cp /lib/libm.so.6 .
# Copying RedHat 7.2 libc causes things to not run on RedHat 7.1.
# cp /lib/libc.so.6 .
cp /lib/ld-linux.so.2 .

chmod 644 *.so*
