#! /bin/csh -f

#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 2001
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

#  Run this script to set up the solaris-intel dynamic libraries.

############################################################

#  $Id$

############################################################

if ($#argv < 1) then
  echo "Usage: dyn_lib_solaris1 <dyn_lib_directory>"
  exit 1
endif

set libdir = $1

set homedir = `pwd`

cd $libdir
$homedir/dyn_lib_solaris2
