#! /bin/csh -f
############################################################

# $Id$

############################################################

limit coredumpsize 0
limit descriptors 256

#set path = ( $path /p/qclic/Code/Qclic/bin.common )
set path = ( $path /p/devise/public/bin )

setenv DEVISE_ROOT    /p/devise

setenv DEVISE_DAT     $DEVISE_ROOT/dat
setenv DEVISE_HOME_TABLE	$DEVISE_ROOT/schema/schema/catalog.dte
setenv DEVISE_ID_FILE		$DEVISE_ROOT/schema/schema/temp_catalog
setenv DEVISE_DEF_FILE		$DEVISE_ROOT/schema/schema/def_file
setenv DEVISE_INDEX_TABLE	$DEVISE_ROOT/schema/schema/sysind.dte
setenv DEVISE_MINMAX_TABLE	$DEVISE_ROOT/schema/schema/minmax.dte
setenv DEVISE_MINMAX_DIR	$DEVISE_ROOT/dat
setenv DEVISE_MATERIAL_DIR	$DEVISE_ROOT/dat
setenv DEVISE_CACHE   $DEVISE_ROOT/cache
setenv DEVISE_SCHEMA  $DEVISE_ROOT/schema/schema
setenv DEVISE_SESSION $DEVISE_ROOT/session
setenv DEVISE_LIB     $DEVISE_ROOT/public/lib
setenv DEVISE_TMP     /tmp/`whoami`-devise-tmp
setenv DEVISE_WORK    /tmp/`whoami`-devise-work
setenv DEVISE_EXEC    $DEVISE_ROOT/public/bin/devise
setenv DEVISE_PALETTE	$DEVISE_ROOT/palette

setenv LM_LIB         $DEVISE_LIB/LM
setenv LM_DAT         /tmp/LM/dat
setenv LM_TMP         /tmp/LM/dat

if (! -f $DEVISE_EXEC) then
  echo "Cannot find Devise executable. Perhaps this platform is not supported?"
  exit 1
endif

$DEVISE_ROOT/run/rmmem
$DEVISE_EXEC $*
$DEVISE_ROOT/run/rmmem
