#! /s/std/bin/perl

#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1998
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

#  This is a script for the jspop to use to kill a devised.  Optional
#  argument is port number devised is listening on, to make sure you
#  kill the right one.

############################################################

#  $Id$

#  $Log$
#  Revision 1.2  1999/02/17 18:48:54  wenger
#  Made this script work even if the devised command has a very long path.
#
#  Revision 1.1  1998/11/03 17:42:49  wenger
#  New script for jspop to use to kill devised.
#

############################################################

if ($#ARGV >= 0) {
    $pattern = "devised -port $ARGV[0]";
    # ww option forces extra-wide output
    open PS, "ps -axww >& 1 |" or die "can't fork: $!";
} else {
    $pattern = "devised";
    # c option prevents path from being shown as part of command name
    open PS, "ps -axc >& 1 |" or die "can't fork: $!";
}

while (<PS>) {
#    print "line: ";
#    print;
    if ($_ =~ /$pattern/) {
	@words = split /  */, $_;
	$pid = @words[1];

        system("kill -INT $pid");
        system sleep 1;
        system("kill -INT $pid");
        system sleep 1;
        system("kill -INT $pid");
    }
}

close PS;
