// ========================================================================
// DEVise Data Visualization Software
// (c) Copyright 2003-2007
// By the DEVise Development Group
// Madison, Wisconsin
// All Rights Reserved.
// ========================================================================

// Under no circumstances is this software to be copied, distributed,
// or altered in any way without prior permission from the DEVise
// Development Group.

// ------------------------------------------------------------------------

// This class implements methods for outputting the summary data to be
// used to select individual data sets in a 3D atomic coordinate
// visualization.

// ------------------------------------------------------------------------

// $Id$

// $Log$
// Revision 1.2  2006/02/01 20:23:12  wenger
// Merged V2_1b4_br_0 thru peptide_cgi_10_8_0_base to the
// trunk.
//
// Revision 1.1.2.5  2005/01/31 23:02:55  wenger
// Merged pistachio_vis_br_0 thru pistachio_vis_br_1a to V2_1b4_br.
//
// Revision 1.1.2.4  2004/12/03 17:18:34  wenger
// Added BMRB accession number, PDB ID (if relevant), timestamp and
// Peptide-CGI version number to Peptide-CGI visualizations.
//
// Revision 1.1.2.3.2.1  2005/01/12 20:46:42  wenger
// Pistachio processing is now integrated into the normal Peptide-CGI
// processing -- the Pistachio visualization is generated autmatically
// if the Pistachio data exists.  (Still needs some cleanup, though.)
// (We generate the Pistachio visualization by generating a temporary
// mmCIF file with coordinates -- that is then run through the normal
// coordinate processing to generate the DEVise file with Pistachio
// coordinates.)
//
// Revision 1.1.2.3  2004/06/16 19:23:31  wenger
// Added headers to data files generated by Peptide-CGI.
//
// Revision 1.1.2.2  2003/05/14 21:45:52  wenger
// Changed "/"s in file names to File.separator (hope I got them all!).
//
// Revision 1.1.2.1  2003/04/22 21:58:16  wenger
// Added package name to peptide-cgi java code and put everything into
// a single jar file; version is now 6.0.
//
// Revision 1.1.4.2  2003/04/09 18:02:14  wenger
// First version of visualization-server capability now in place; still
// needs some fixes.
//
// Revision 1.1.4.1  2003/01/14 16:51:49  wenger
// Merged V2_1b3_br_0 thru V2_1b3_br_end to V2_1b4_br.
//
// Revision 1.1.2.5  2002/11/01 17:40:15  wenger
// Fixed bug 013 (s2d fails if no write permission on output files).
//
// Revision 1.1.2.4  2002/10/31 22:17:36  wenger
// Changed Exception output to use toString() instead of getMessage()
// because that (at least sometimes) produces more complete information.
//
// Revision 1.1.2.3  2002/08/21 20:40:50  wenger
// Selection of data set to view now works, but there is not yet selection
// on the data linked to the 3D view.
//
// Revision 1.1.2.2  2002/08/21 15:59:38  wenger
// Changed all schemas to have Residue_seq_code as the attribute name
// we want to display for the sequence number, to make setting up the
// 4096-type 3D visualizations easier.
//
// Revision 1.1.2.1  2002/08/21 14:21:30  wenger
// Working on 4096-type 3D visualization -- added data and view to show
// list of available data sets.
//

// ========================================================================

package star2devise;

import java.util.*;
import java.io.*;

public class S2DSummaryData
{
    //===================================================================
    // VARIABLES

    private static final int DEBUG = 0;

    private String _name;
    private String _dataDir;
    private Vector _dataSets;

    //===================================================================
    // PUBLIC METHODS

    //-------------------------------------------------------------------
    /**
     * Constructor.
     * @param The data name.
     * @param The data directory.
     * @param The list of available data sets.
     */
    public S2DSummaryData(String name, String dataDir, Vector dataSets)
    {
        if (doDebugOutput(11)) {
	    System.out.println("S2DSummaryData.S2DSummaryData(" +
	      name + " " + dataDir + ")");
        }

	_name = name;
	_dataDir = dataDir;
    	_dataSets = dataSets;
    }

    //-------------------------------------------------------------------
    /**
     * Write the summary data.
     */
    public void writeSummaryData() throws S2DException
    {
        if (doDebugOutput(11)) {
	    System.out.println("S2DSummaryData.writeSummaryData()");
            System.out.println("Data sets: ");
            for (int index = 0; index < _dataSets.size(); index++) {
                S2DDatasetInfo info =
		  (S2DDatasetInfo)_dataSets.elementAt(index);
                System.out.println("  " + info.getName() + "\t" +
                  info.getDataSourceName() + "\t" + info.getYAttribute());
            }
        }

	try {
	    FileWriter writer = S2DFileWriter.create(_dataDir +
	      File.separator + _name + S2DNames.SUMMARY_DATA_SUFFIX +
	        S2DNames.DAT_SUFFIX);
	    writer.write("# Data: summary of available datasets for " +
	      _name + " 3D visualization\n");
	    writer.write("# Schema: bmrb-summary\n");
	    writer.write("# Attributes: name; data_source; y_attribute\n");
            writer.write("# Peptide-CGI version: " +
	      S2DMain.PEP_CGI_VERSION + "\n");
            writer.write("# Generation date: " +
	      S2DMain.getTimestamp() + "\n");
	    writer.write("#\n");

            for (int index = 0; index < _dataSets.size(); index++) {
                S2DDatasetInfo info =
		  (S2DDatasetInfo)_dataSets.elementAt(index);
                writer.write(info.getName() + "\t" +
		  info.getDataSourceName() + "\t" +
		  "$" + info.getYAttribute() + "\n");
	    }

	    writer.close();

        } catch (IOException ex) {
	    System.err.println("IOException writing summary data values: " +
	      ex.toString());
	    throw new S2DError("Can't write summary data values");

	}
    }

    //===================================================================
    // PRIVATE METHODS

    //-------------------------------------------------------------------
    // Determine whether to do debug output based on the current debug
    // level settings and the debug level of the output.
    private static boolean doDebugOutput(int level)
    {
    	if (DEBUG >= level || S2DMain._verbosity >= level) {
	    if (level > 0) System.out.print("DEBUG " + level + ": ");
	    return true;
	}

	return false;
    }
}

// ========================================================================

