#! /bin/csh -f
############################################################

# $Id$

############################################################

setenv DEVISE_ROOT    /p/devise

setenv DEVISE_DAT     $DEVISE_ROOT/dat
setenv DEVISE_HOME_TABLE	$DEVISE_ROOT/schema/schema/catalog.dte
setenv DEVISE_ID_FILE		$DEVISE_ROOT/schema/schema/temp_catalog
setenv DEVISE_DEF_FILE		$DEVISE_ROOT/schema/schema/def_file
setenv DEVISE_INDEX_TABLE	$DEVISE_ROOT/schema/schema/sysind.dte
setenv DEVISE_MINMAX_TABLE	$DEVISE_ROOT/schema/schema/minmax.dte
setenv DEVISE_MINMAX_DIR	$DEVISE_ROOT/dat
setenv DEVISE_MATER_DIR		$DEVISE_ROOT/dat
setenv DEVISE_CACHE   $DEVISE_ROOT/cache
setenv DEVISE_SCHEMA  $DEVISE_ROOT/schema/schema
setenv DEVISE_SESSION $DEVISE_ROOT/session
setenv DEVISE_LIB     $DEVISE_ROOT/`whoami`/lib
setenv DEVISE_TMP     /tmp/`whoami`-devise-tmp
setenv DEVISE_WORK    /tmp/`whoami`-devise-work
setenv DEVISE_EXEC    bin/ams/ams
setenv DEVISE_PALETTE	$DEVISE_ROOT/palette
setenv DEVISE_LOG_DIR		$DEVISE_TMP

if (! -f $DEVISE_EXEC) then
  echo "Cannot find Devise executable ($DEVISE_EXEC)."
  echo "Perhaps you haven't compiled for this platform?"
  exit 1
endif

$DEVISE_ROOT/run/rmmem
$DEVISE_EXEC $*
$DEVISE_ROOT/run/rmmem
