#! /bin/csh -f

setenv DEVISE_ROOT    /p/devise

setenv DEVISE_EXEC    bin/generic/deviseb

if (! -f $DEVISE_EXEC) then
  echo "Cannot find Devise executable ($DEVISE_EXEC)."
  echo "Perhaps you haven't compiled for this platform?"
  exit 1
endif

$DEVISE_EXEC $*
