#! /bin/csh -f
############################################################

# $Id$

############################################################

limit coredumpsize 0
limit descriptors 256

setenv DEVISE_ROOT    /p/devise/shilpa/devise

setenv DEVISE_DAT     $DEVISE_ROOT/dat
setenv DEVISE_CACHE   $DEVISE_ROOT/cache
setenv DEVISE_SCHEMA  $DEVISE_ROOT/schema/schema
#setenv DEVISE_SESSION /p/devise/session/ssl
setenv DEVISE_SESSION $DEVISE_ROOT/session
setenv DEVISE_LIB     $DEVISE_ROOT/lib
setenv DEVISE_TMP     /tmp/devise-tmp
setenv DEVISE_WORK    /tmp/devise-work
setenv DEVISE_EXEC    bin/generic/generic
# LM stuff
setenv LM_LIB         $DEVISE_LIB/LM 
setenv LM_DAT         $DEVISE_TMP 
setenv LM_TMP         $DEVISE_TMP
if (! -f $DEVISE_EXEC) then
  echo "Cannot find Devise executable ($DEVISE_EXEC)."
  echo "Perhaps you haven't compiled for this platform?"
  exit 1
endif

$DEVISE_EXEC $*
rmipcs 
ipcs
