#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1992-1997
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  $Id$

#  $Log$
#  Revision 1.1  1997/05/28 20:48:26  wenger
#  Added directories and makefiles for layout mananger to compile for hp,
#  linux, solsparc, and sun.
#

############################################################

ARCH_FLAGS = -DLINUX -I/usr/include/tcl

VPATH = ../../LM
include $(VPATH)/Makefile.base
include $(VPATH)/Makefile.linux
