#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <iostream.h>
#include <fstream.h>
#include <ctype.h>
#include <String.h>


#include "Engine.h"
#include "exception.h"

// #define DQL_DUMMY

int dql(int argc, char **argv)
{
  char *sqlCommand = argv[1];
  char *cachefile = argv[2];
  char *schemafile = argv[3];
  char *schematype = argv[4];

  String query = String(sqlCommand);
#ifndef DQL_DUMMY
  Engine engine(query);
  engine.optimize();
  CATCH(currExcept->display(); currExcept = NULL; return -1);
  int numFlds = engine.getNumFlds();
  String* attrs = engine.getAttributeNames();
  String* types = engine.getTypeIDs();
#else
  int numFlds = 2;
  String* attrs = new String[2];
  attrs[0] = "dummy1";
  attrs[1] = "dummy2";
  String* types = new String[2];
  types[0] = "int";
  types[1] = "int";
#endif

  ofstream sout(schemafile,ios::out);
  assert(sout);

  sout << "type " << schematype << " ascii " << endl;
  sout << "comment #" << endl;
  sout << "separator ' ' "<< endl;
  for(int i = 0; i < numFlds; i++){
	  sout << "attr " << attrs[i] << " " << types[i] << endl;
  }
  sout.close();

  ofstream fout(cachefile,ios::out);
  assert(fout);

#ifdef DQL_DUMMY
  fout << "1 2" << endl;
  fout << "3 4" << endl;
#else
  fout << "# Generated by DTE as response to"<< endl;
  fout << "# "<< sqlCommand << endl;
  Tuple* tup;
	while((tup = engine.getNext())){
		for(int i = 0; i < numFlds; i++){
			displayAs(fout, tup[i], types[i]);
			fout << " ";
		}
		fout << endl;
	}
#endif
  fout.close();
  return 0;
}
