ARCH_FLAGS = -DPENTIUM -I/usr/X11R6/include \
	-I../tcl/include -I../../graphics -I../../graphics.new
ARCH_LDFLAGS = -L /usr/X11R6/lib -L ../tcl/lib -R /usr/X11R6/lib 
#CC = CC
VPATH = ../../multi
include $(VPATH)/Makefile.solaris
# DO NOT DELETE THIS LINE -- make depend depends on it.
