#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 2005
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  This Makefile has settings that apply to everything compiled
#  on the Intel/RedHat 7.3 Linux architecture.

############################################################

#  $Id$

#  $Log$
#  Revision 1.1.2.1  2005/10/20 20:29:54  wenger
#  Some errno-related fixes; added RH 7.3 stuff; clarifying note
#  in linux setup script.
#

############################################################

# Compiled on icnm.cerm.unifi.it, 2005-10-20.

CC = g++ 
C  = gcc 

TCL_TK_DIR = /usr
TCL_TK_INCLUDE = -I$(TCL_TK_DIR)/include
TCL_TK_LIBDIR = -L$(TCL_TK_DIR)/lib
TCL_TK_LIBS = -ltk8.3 -ltcl8.3

XLIB_DIR = /usr/X11R6
XLIB_INCLUDE = -I$(XLIB_DIR)/include
XLIB_LIBDIR = -L$(XLIB_DIR)/lib

ARCH_FLAGS = -DLINUX $(XLIB_INCLUDE) $(TCL_TK_INCLUDE)
ARCH_FLAGS += -DSBM_PROCESS -DSBM_SHARED_MEMORY

ARCH_ENDIAN =
