#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 1998
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  $Id$

#  $Log$
#  Revision 1.1  1998/11/19 22:42:13  wenger
#  Implemented non-DTE version of DEVise (new code handles data source catalog
#  functions; Tables, SQLViews, etc., are not implemented).
#

############################################################

include ../Makefile.config

ARCH_LDFLAGS = 
ARCH_LDPOST  =

VPATH = ../../src/data
include $(VPATH)/Makefile.base
include Makefile.depend
