#  ========================================================================
#  DEVise Data Visualization Software
#  (c) Copyright 2007
#  By the DEVise Development Group
#  Madison, Wisconsin
#  All Rights Reserved.
#  ========================================================================
#
#  Under no circumstances is this software to be copied, distributed,
#  or altered in any way without prior permission from the DEVise
#  Development Group.

############################################################

#  This Makefile has settings that apply to everything compiled
#  on the Intel/RHEL5 Linux platform.

############################################################

#  $Id$

#  $Log$

############################################################

# Compiled on manta, 2007-12-27.

CC = g++ 
C  = gcc 

TCL_TK_DIR = /usr/lib
TCL_TK_INCLUDE = -I/s/tcl/include
TCL_TK_LIBDIR = -L$(TCL_TK_DIR)/lib
TCL_TK_LIBS = -ltk8.4 -ltcl8.4

XLIB_DIR = /usr/lib
XLIB_INCLUDE = -I$(XLIB_DIR)/include
XLIB_LIBDIR = -L$(XLIB_DIR)/lib

ARCH_FLAGS = -DLINUX $(XLIB_INCLUDE) $(TCL_TK_INCLUDE)
ARCH_FLAGS += -DSBM_PROCESS -DSBM_SHARED_MEMORY

ARCH_ENDIAN =
