#! /bin/csh -f

# Tests bug 065 (problem Jundong ran into on 2008-06-23).

set result = 0

rm -f */test53_out*
rm -f */*/test53_out*

echo -n "Processing NMR-STAR: "
./uvd -file test_data/bmr15803_3.str -name test53_out -force -check_pct
if ($status != 0) then
  echo "First invocation of uvd failed!"
  set result = 1
endif


echo "Checking output files"

#TEMP -- no session files here!!!!
set files = ( data_dir/uvd/test53_outam1.dat \
	data_dir/uvd/test53_outamac1.dat \
	data_dir/uvd/test53_outas1.dat \
	data_dir/uvd/test53_outas2.dat \
	data_dir/uvd/test53_outc1.dat \
	data_dir/uvd/test53_outc2.dat \
	data_dir/uvd/test53_outd1.dat \
	data_dir/uvd/test53_outd2.dat \
	data_dir/uvd/test53_outhn1.dat \
	data_dir/uvd/test53_outhn2.dat \
	data_dir/uvd/test53_outmd.dat \
	data_dir/uvd/test53_outp1.dat \
	data_dir/uvd/test53_outp2.dat \
	data_dir/uvd/test53_outrc1.dat \
	data_dir/uvd/test53_outrc2.dat \
	data_dir/uvd/test53_outrl.dat \
	html_dir/uvd/test53_outam1.html \
	html_dir/uvd/test53_outam1_large.html \
	html_dir/uvd/test53_outas1.html \
	html_dir/uvd/test53_outas1_large.html \
	html_dir/uvd/test53_outas2.html \
	html_dir/uvd/test53_outas2_large.html \
	html_dir/uvd/test53_outc1.html \
	html_dir/uvd/test53_outc1_large.html \
	html_dir/uvd/test53_outc2.html \
	html_dir/uvd/test53_outc2_large.html \
	html_dir/uvd/test53_outd1.html \
	html_dir/uvd/test53_outd1_large.html \
	html_dir/uvd/test53_outd2.html \
	html_dir/uvd/test53_outd2_large.html \
	html_dir/uvd/test53_outhn1.html \
	html_dir/uvd/test53_outhn1_large.html \
	html_dir/uvd/test53_outp1.html \
	html_dir/uvd/test53_outp1_large.html \
	html_dir/uvd/test53_outp2.html \
	html_dir/uvd/test53_outp2_large.html \
	html_dir/uvd/test53_outy.html \
	html_dir/uvd/test53_outy_large.html )
	
foreach file ($files)
  if (! -f $file) then
    echo "  Output file $file is missing"
    set result = 1
  endif
end


echo -n "Test53 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
