#! /bin/csh -f

# This is to test NMR-STAR 3.0 processing.

set result = 0

rm -r -f */5076*

echo -n "Processing NMR-STAR and mmCIF: "
./s2d -nomail -file test_data/bmr5076.str.nmrstr -name 5076 -do_pdb 2 -force \
  -check_res_list -check_pct
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif


echo "Checking output files"

set files = ( data_dir/5076ac1.dat data_dir/5076as1.dat data_dir/5076as2.dat \
	data_dir/5076as3.dat data_dir/5076d1.dat data_dir/5076d2.dat \
	data_dir/5076d3.dat data_dir/5076g1.dat data_dir/5076g2.dat \
	data_dir/5076g3.dat data_dir/5076hn1.dat data_dir/5076hn2.dat \
	data_dir/5076hn3.dat data_dir/5076md.dat data_dir/5076n1.dat \
	data_dir/5076n2.dat data_dir/5076p1.dat data_dir/5076p2.dat \
	data_dir/5076p3.dat data_dir/5076rc1.dat data_dir/5076rc2.dat \
	data_dir/5076rc3.dat data_dir/5076rl.dat \
	data_dir/5076t11.dat data_dir/5076t12.dat \
	data_dir/5076t13.dat data_dir/5076t14.dat data_dir/5076t15.dat \
	data_dir/5076t16.dat html_dir/5076/5076ac1.html html_dir/5076/5076as1.html \
	html_dir/5076/5076as2.html html_dir/5076/5076as3.html html_dir/5076/5076d1.html \
	html_dir/5076/5076d2.html html_dir/5076/5076d3.html html_dir/5076/5076g1.html \
	html_dir/5076/5076g2.html html_dir/5076/5076g3.html html_dir/5076/5076hn1.html \
	html_dir/5076/5076hn2.html html_dir/5076/5076hn3.html html_dir/5076/5076n1.html \
	html_dir/5076/5076n2.html html_dir/5076/5076p1.html html_dir/5076/5076p2.html \
	html_dir/5076/5076p3.html html_dir/5076/5076t11.html html_dir/5076/5076t12.html \
	html_dir/5076/5076t13.html html_dir/5076/5076t14.html html_dir/5076/5076t15.html \
	html_dir/5076/5076t16.html html_dir/5076/5076y.html html_dir/5076/5076y_large.html \
	session_dir/5076/5076ac1.ds \
	session_dir/5076/5076acdd session_dir/5076/5076as1.ds session_dir/5076/5076as2.ds \
	session_dir/5076/5076as3.ds session_dir/5076/5076d1.ds session_dir/5076/5076d2.ds \
	session_dir/5076/5076d3.ds session_dir/5076/5076g1.ds session_dir/5076/5076g2.ds \
	session_dir/5076/5076g3.ds session_dir/5076/5076hn1.ds session_dir/5076/5076hn2.ds \
	session_dir/5076/5076hn3.ds session_dir/5076/5076n1.ds session_dir/5076/5076n2.ds \
	session_dir/5076/5076p1.ds session_dir/5076/5076p2.ds session_dir/5076/5076p3.ds \
	session_dir/5076/5076t11.ds session_dir/5076/5076t12.ds session_dir/5076/5076t13.ds \
	session_dir/5076/5076t14.ds session_dir/5076/5076t15.ds session_dir/5076/5076t16.ds \
	data_dir/5076am1.dat \
	html_dir/5076/5076am1.html \
	session_dir/5076/5076am1.ds \
	html_dir/5076/5076ac1_large.html \
	html_dir/5076/5076am1_large.html \
	html_dir/5076/5076am2_large.html \
	html_dir/5076/5076am3_large.html \
	html_dir/5076/5076as1_large.html \
	html_dir/5076/5076as2_large.html \
	html_dir/5076/5076as3_large.html \
	html_dir/5076/5076d1_large.html \
	html_dir/5076/5076d2_large.html \
	html_dir/5076/5076d3_large.html \
	html_dir/5076/5076g1_large.html \
	html_dir/5076/5076g2_large.html \
	html_dir/5076/5076g3_large.html \
	html_dir/5076/5076hn1_large.html \
	html_dir/5076/5076hn2_large.html \
	html_dir/5076/5076hn3_large.html \
	html_dir/5076/5076n1_large.html \
	html_dir/5076/5076n2_large.html \
	html_dir/5076/5076p1_large.html \
	html_dir/5076/5076p2_large.html \
	html_dir/5076/5076p3_large.html \
	html_dir/5076/5076t11_large.html \
	html_dir/5076/5076t12_large.html \
	html_dir/5076/5076t13_large.html \
	html_dir/5076/5076t14_large.html \
	html_dir/5076/5076t15_large.html \
	html_dir/5076/5076t16_large.html \
	data_dir/5076hc1.dat \
	data_dir/5076hc2.dat \
	data_dir/5076hc3.dat \
	html_dir/5076/5076hc1.html \
	html_dir/5076/5076hc1_large.html \
	html_dir/5076/5076hc2.html \
	html_dir/5076/5076hc2_large.html \
	html_dir/5076/5076hc3.html \
	html_dir/5076/5076hc3_large.html \
	session_dir/5076/5076hc1.ds \
	session_dir/5076/5076hc2.ds \
	session_dir/5076/5076hc3.ds )

foreach file ($files)
  if (! -f $file) then
    echo "  Output file $file is missing"
    set result = 1
  endif
end


echo -n "Test10 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
