#! /bin/csh -f

# Tests "upload and visualize" mode.

set result = 0

rm -f */test49_out*
rm -f */*/test49_out*

echo -n "Processing NMR-STAR: "
./uvd -file test_data/20070430_12345.str -name test49_out -force -do_lacs 1 \
  -check_pct
if ($status != 0) then
  echo "First invocation of uvd failed!"
  set result = 1
endif


echo "Checking output files"

set files = ( data_dir/uvd/test49_outam1.dat \
	data_dir/uvd/test49_outamac1.dat \
	data_dir/uvd/test49_outas1.dat \
	data_dir/uvd/test49_outc1.dat \
	data_dir/uvd/test49_outd1.dat \
	data_dir/uvd/test49_outg1.dat \
	data_dir/uvd/test49_outhc1.dat \
	data_dir/uvd/test49_outhn1.dat \
	data_dir/uvd/test49_outlacsc1.dat \
	data_dir/uvd/test49_outlacsc2.dat \
	data_dir/uvd/test49_outlacsc3.dat \
	data_dir/uvd/test49_outlacsc4.dat \
	data_dir/uvd/test49_outlacsl1.dat \
	data_dir/uvd/test49_outlacsl2.dat \
	data_dir/uvd/test49_outlacsl3.dat \
	data_dir/uvd/test49_outlacsl4.dat \
	data_dir/uvd/test49_outlacsp1.dat \
	data_dir/uvd/test49_outlacsp2.dat \
	data_dir/uvd/test49_outlacsp3.dat \
	data_dir/uvd/test49_outlacsp4.dat \
	data_dir/uvd/test49_outmd.dat \
	data_dir/uvd/test49_outn1.dat \
	data_dir/uvd/test49_outn2.dat \
	data_dir/uvd/test49_outn3.dat \
	data_dir/uvd/test49_outn4.dat \
	data_dir/uvd/test49_outn5.dat \
	data_dir/uvd/test49_outn6.dat \
	data_dir/uvd/test49_outn7.dat \
	data_dir/uvd/test49_outn8.dat \
	data_dir/uvd/test49_outn9.dat \
	data_dir/uvd/test49_outp1.dat \
	data_dir/uvd/test49_outrc1.dat \
	data_dir/uvd/test49_outrl.dat \
	data_dir/uvd/test49_outt11.dat \
	data_dir/uvd/test49_outt12.dat \
	data_dir/uvd/test49_outt13.dat \
	data_dir/uvd/test49_outt21.dat \
	data_dir/uvd/test49_outt22.dat \
	data_dir/uvd/test49_outt23.dat \
	html_dir/uvd/test49_outam1.html \
	html_dir/uvd/test49_outam1_large.html \
	html_dir/uvd/test49_outas1.html \
	html_dir/uvd/test49_outas1_large.html \
	html_dir/uvd/test49_outc1.html \
	html_dir/uvd/test49_outc1_large.html \
	html_dir/uvd/test49_outd1.html \
	html_dir/uvd/test49_outd1_large.html \
	html_dir/uvd/test49_outg1.html \
	html_dir/uvd/test49_outg1_large.html \
	html_dir/uvd/test49_outhc1.html \
	html_dir/uvd/test49_outhc1_large.html \
	html_dir/uvd/test49_outhn1.html \
	html_dir/uvd/test49_outhn1_large.html \
	html_dir/uvd/test49_outlacs1.html \
	html_dir/uvd/test49_outlacs1_large.html \
	html_dir/uvd/test49_outlacs2.html \
	html_dir/uvd/test49_outlacs2_large.html \
	html_dir/uvd/test49_outlacs3.html \
	html_dir/uvd/test49_outlacs3_large.html \
	html_dir/uvd/test49_outlacs4.html \
	html_dir/uvd/test49_outlacs4_large.html \
	html_dir/uvd/test49_outn1.html \
	html_dir/uvd/test49_outn1_large.html \
	html_dir/uvd/test49_outn2.html \
	html_dir/uvd/test49_outn2_large.html \
	html_dir/uvd/test49_outn3.html \
	html_dir/uvd/test49_outn3_large.html \
	html_dir/uvd/test49_outn4.html \
	html_dir/uvd/test49_outn4_large.html \
	html_dir/uvd/test49_outn5.html \
	html_dir/uvd/test49_outn5_large.html \
	html_dir/uvd/test49_outn6.html \
	html_dir/uvd/test49_outn6_large.html \
	html_dir/uvd/test49_outn7.html \
	html_dir/uvd/test49_outn7_large.html \
	html_dir/uvd/test49_outn8.html \
	html_dir/uvd/test49_outn8_large.html \
	html_dir/uvd/test49_outn9.html \
	html_dir/uvd/test49_outn9_large.html \
	html_dir/uvd/test49_outp1.html \
	html_dir/uvd/test49_outp1_large.html \
	html_dir/uvd/test49_outt11.html \
	html_dir/uvd/test49_outt11_large.html \
	html_dir/uvd/test49_outt12.html \
	html_dir/uvd/test49_outt12_large.html \
	html_dir/uvd/test49_outt13.html \
	html_dir/uvd/test49_outt13_large.html \
	html_dir/uvd/test49_outt21.html \
	html_dir/uvd/test49_outt21_large.html \
	html_dir/uvd/test49_outt22.html \
	html_dir/uvd/test49_outt22_large.html \
	html_dir/uvd/test49_outt23.html \
	html_dir/uvd/test49_outt23_large.html \
	html_dir/uvd/test49_outy.html \
	html_dir/uvd/test49_outy_large.html \
	session_dir/.uvd/test49_outacdd \
	session_dir/.uvd/test49_outam1.ds \
	session_dir/.uvd/test49_outas1.ds \
	session_dir/.uvd/test49_outc1.ds \
	session_dir/.uvd/test49_outd1.ds \
	session_dir/.uvd/test49_outg1.ds \
	session_dir/.uvd/test49_outhc1.ds \
	session_dir/.uvd/test49_outhn1.ds \
	session_dir/.uvd/test49_outlacs1.ds \
	session_dir/.uvd/test49_outlacs2.ds \
	session_dir/.uvd/test49_outlacs3.ds \
	session_dir/.uvd/test49_outlacs4.ds \
	session_dir/.uvd/test49_outn1.ds \
	session_dir/.uvd/test49_outn2.ds \
	session_dir/.uvd/test49_outn3.ds \
	session_dir/.uvd/test49_outn4.ds \
	session_dir/.uvd/test49_outn5.ds \
	session_dir/.uvd/test49_outn6.ds \
	session_dir/.uvd/test49_outn7.ds \
	session_dir/.uvd/test49_outn8.ds \
	session_dir/.uvd/test49_outn9.ds \
	session_dir/.uvd/test49_outo1.ds \
	session_dir/.uvd/test49_outp1.ds \
	session_dir/.uvd/test49_outt11.ds \
	session_dir/.uvd/test49_outt12.ds \
	session_dir/.uvd/test49_outt13.ds \
	session_dir/.uvd/test49_outt21.ds \
	session_dir/.uvd/test49_outt22.ds \
	session_dir/.uvd/test49_outt23.ds )
	
foreach file ($files)
  if (! -f $file) then
    echo "  Output file $file is missing"
    set result = 1
  endif
end

set file = "data_dir/uvd/test49_outt11.dat"
set line = "3 ASP N 1.030 0.031"
source tests/check4line
set line = "155 ARG NE 1.830 0.110"
source tests/check4line


echo -n "Test49 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
