#! /bin/csh -f

# Tests visualization of SPARTA-calculated theoretical deltashifts
# (NMR-STAR 2.1 file).

set result = 0

rm -f */16387*

echo -n "Processing NMR-STAR: "
./s2d -bmrbid 16387 -force -check_res_list \
  -check_pct -sparta_file test_data/bmr16387_sparta.str_v2
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif

source tests/test_sparta5_check

#TEMP? (until SPARTA output is fixed)
set file = "data_dir/16387sd1.dat"
set line = '^1 1 2 GLU 0.115 -1.11 -0.538 -0.198 -4.886 0.4$'
source tests/check4line
set line = '^1 1 80 HIS -1.023 0.0 3.746 -2.65 3.312 -0.482$'
source tests/check4line
set line = '^1 20 2 GLU -0.057 -1.07 -0.442 -1.193 -4.161 0.0040$'
source tests/check4line
set line = '^1 20 80 HIS -0.155 0.0 2.095 -0.392 0.868 -0.193$'
source tests/check4line
set line = '^1 0 2 GLU 0.095 -0.681 -0.653 -0.717 -3.482 -0.051$'
source tests/check4line
set line = '^1 0 80 HIS -0.369 0.0 2.113 -0.761 1.636 -0.366$'
source tests/check4line


echo -n "Test_sparta5 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
