#! /bin/csh -f

# Test of torsion angle restraints -- use an explicitly-specified
# restraint file (from remediated restraints).

set result = 0

rm -r -f */16270*

echo -n "Processing NMR-STAR: "
./make_view number=16270
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif
mv tmp/s2d.out tmp/s2d.out1

echo -n "Processing mmCIF and torsion angle restraints: "
./make_view number=16270\&pdbid=2kid\&coord_index=2\&do_rrtar=3
if ($status != 0) then
  echo "Second invocation of s2d failed!"
  set result = 1
endif


source tests/test_tar8_check


echo -n "Test_tar8imv result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
