#! /bin/csh -f

# Tests BMRB 16275 (has 2D Sparky peak list).

set result = 0

rm -r -f */16275*

echo -n "Processing NMR-STAR: "
./s2d -nomail -name 16275 -file test_data/bmr16275.str -force -check_res_list -check_pct -peakonly
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif
mv tmp/s2d.out tmp/test_peak11.out


source tests/test_peak11_check


echo -n "Test_peak11 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
