#! /bin/csh -f

# Test restraints using restraint grid data.  2oqs has data for two
# entity assemblies.

set result = 0

rm -f */15209*

echo -n "Processing NMR-STAR: "
./make_view number=15209
if ($status != 0) then
  echo "First invocation of make_view failed!"
  set result = 1
endif
mv tmp/s2d.out tmp/s2d.out1

echo -n "Processing mmCIF and distance restraints: "
./make_view number=15209\&pdbid=2oqs\&coord_index=1\&do_dist=3
if ($status != 0) then
  echo "Second invocation of make_view failed!"
  set result = 1
endif


source tests/test_dist3rg_check


echo -n "Test_dist3rgimv result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
