#! /bin/csh -f

# Tests BMRB 16576 (has peak lists).

set result = 0

rm -r -f */16576*

echo -n "Processing NMR-STAR: "
./s2d -nomail -bmrbid 16576 -force -check_res_list -check_pct \
  -star_url http://www.bmrb.wisc.edu/ftp/pub/bmrb/entry_lists/nmr-star2.1/
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif
mv tmp/s2d.out tmp/test_peak2_21.out


source tests/test_peak2_check


echo -n "Test_peak2_21 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
