#! /bin/csh -f

# Tests visualization of SPARTA-calculated theoretical deltashifts
# (NMR-STAR 3.1 file).

set result = 0

rm -r -f */16385*

echo -n "Processing NMR-STAR: "
./s2d -file test_data/sd16385_3.str -name 16385 -force -check_res_list \
  -check_pct -sparta_file test_data/bmr16385_3_sparta.str
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif

source tests/test_sparta3_check


echo -n "Test_sparta3_3 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
