#! /bin/csh -f

# Tests processing of methyl groups for 1H-13C simulated spectrum.

set result = 0

rm -r -f */*/methyl1_out*
rm -r -f */.*/methyl1_out*

echo -n "Processing NMR-STAR: "
./uvd -file test_data/test_methyl1_3_0.str -name methyl1_out -force -check_pct
if ($status != 0) then
  echo "First invocation of uvd failed!"
  set result = 1
endif

source tests/test_methyl1_check

# 3.0-specific checks for methyl groups.
set file = "data_dir/uvd/methyl1_outhc1.dat"

# ALA
set line = '^1.51 18.13 HB3 CB 12 ALA 1 methyl1_out A$'
source tests/check4line
set line = '^1.51 18.13 HB2 CB 12 ALA 1 methyl1_out A$'
source tests/check4line
set line = '^1.51 18.13 HB1 CB 12 ALA 1 methyl1_out A$'
source tests/check4line

# ILE
set line = '^0.84 17.45 HG23 CG2 8 ILE 1 methyl1_out I$'
source tests/check4line
set line = '^0.84 17.45 HG22 CG2 8 ILE 1 methyl1_out I$'
source tests/check4line
set line = '^0.84 17.45 HG21 CG2 8 ILE 1 methyl1_out I$'
source tests/check4line
set line = '^0.86 12.71 HD13 CD1 8 ILE 1 methyl1_out I$'
source tests/check4line
set line = '^0.86 12.71 HD12 CD1 8 ILE 1 methyl1_out I$'
source tests/check4line
set line = '^0.86 12.71 HD11 CD1 8 ILE 1 methyl1_out I$'
source tests/check4line

# LEU
set line = '^0.863 23.893 HD23 CD2 29 LEU 1 methyl1_out L$'
source tests/check4line
set line = '^0.863 23.893 HD22 CD2 29 LEU 1 methyl1_out L$'
source tests/check4line
set line = '^0.863 23.893 HD21 CD2 29 LEU 1 methyl1_out L$'
source tests/check4line
set line = '^1.028 26.184 HD13 CD1 29 LEU 1 methyl1_out L$'
source tests/check4line
set line = '^1.028 26.184 HD12 CD1 29 LEU 1 methyl1_out L$'
source tests/check4line
set line = '^1.028 26.184 HD11 CD1 29 LEU 1 methyl1_out L$'
source tests/check4line

# MET
set line = '^2.12 14.9 HE3 CE 28 MET 1 methyl1_out M$'
source tests/check4line
set line = '^2.12 14.9 HE2 CE 28 MET 1 methyl1_out M$'
source tests/check4line
set line = '^2.12 14.9 HE1 CE 28 MET 1 methyl1_out M$'
source tests/check4line

# THR
set line = '^1.3 21.99 HG22 CG2 18 THR 1 methyl1_out T$'
source tests/check4line
set line = '^1.3 21.99 HG21 CG2 18 THR 1 methyl1_out T$'
source tests/check4line
set line = '^1.3 21.99 HG23 CG2 18 THR 1 methyl1_out T$'
source tests/check4line

# VAL
#TEMP -- hmm -- should all of these really have the same values?
set line = '^1.01 21.48 HG22 CG2 19 VAL 1 methyl1_out V$'
source tests/check4line
set line = '^1.01 21.48 HG21 CG2 19 VAL 1 methyl1_out V$'
source tests/check4line
set line = '^1.01 21.48 HG23 CG2 19 VAL 1 methyl1_out V$'
source tests/check4line
set line = '^1.1 22.41 HG13 CG1 19 VAL 1 methyl1_out V$'
source tests/check4line
set line = '^1.1 22.41 HG12 CG1 19 VAL 1 methyl1_out V$'
source tests/check4line
set line = '^1.1 22.41 HG11 CG1 19 VAL 1 methyl1_out V$'
source tests/check4line

echo -n "Test_methyl1_3 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
