#! /bin/csh -f

# Test star.getAndFilterOptionalFrameValues

set result = 0

rm -f */5085*

echo -n "Processing NMR-STAR: "
./s2d -nomail -name 5085 -file test_data/bmr5085_3.str -force -check_pct
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif

source tests/test61_check


echo -n "Test61_3 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
