#! /bin/csh -f

# Test PDB-only torsion angle processing, using an explicitly-specified
# restraint file.

set result = 0

rm -f */tar_1brv*

echo -n "Processing mmCIF and torsion angle restraints: "
./s2d -nomail -name tar_1brv -pdbid 1brv -coord_index 1 -force \
  -tar_file test_data/1brv_ta.str -do_tar 3 -check_res_list -check_pct
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif


source tests/test_tar1p_check


echo -n "Test_tar1p result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
