#! /bin/csh -f

# Test fix for bug 090 (torsion angle visualization for 15418/2JTT doesn't
# work right).

set result = 0

rm -f */15418*

echo -n "Processing NMR-STAR: "
./s2d -bmrbid 15418 -force -check_res_list -check_pct 
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif
mv tmp/s2d.out tmp/s2d.out1

echo -n "Processing mmCIF and torsion angle restraints: "
./s2d -nomail -bmrbid 15418 -pdbid 2JTT -coord_index 5 -force \
  -do_tar 3 -do_rrtar 3 -check_res_list -check_pct
if ($status != 0) then
  echo "Second invocation of s2d failed!"
  set result = 1
endif


echo "Checking output files"

set files = ( data_dir/15418ac5.dat \
	data_dir/15418am1.dat \
	data_dir/15418am2.dat \
	data_dir/15418amac1.dat \
	data_dir/15418amac2.dat \
	data_dir/15418as1.dat \
	data_dir/15418as2.dat \
	data_dir/15418c2.dat \
	data_dir/15418d1.dat \
	data_dir/15418d2.dat \
	data_dir/15418hc1.dat \
	data_dir/15418hc2.dat \
	data_dir/15418hn1.dat \
	data_dir/15418hn2.dat \
	data_dir/15418md.dat \
	data_dir/15418p1.dat \
	data_dir/15418p2.dat \
	data_dir/15418rc1.dat \
	data_dir/15418rc2.dat \
	data_dir/15418rl.dat \
	data_dir/15418rrac5.dat \
	data_dir/15418rrtar5.dat \
	data_dir/15418rrtar-md5.dat \
	data_dir/15418tar5.dat \
	data_dir/15418tar-md5.dat \
	html_dir/15418ac5.html \
	html_dir/15418ac5_large.html \
	html_dir/15418am1.html \
	html_dir/15418am1_large.html \
	html_dir/15418am2.html \
	html_dir/15418am2_large.html \
	html_dir/15418as1.html \
	html_dir/15418as1_large.html \
	html_dir/15418as2.html \
	html_dir/15418as2_large.html \
	html_dir/15418c2.html \
	html_dir/15418c2_large.html \
	html_dir/15418d1.html \
	html_dir/15418d1_large.html \
	html_dir/15418d2.html \
	html_dir/15418d2_large.html \
	html_dir/15418hc1.html \
	html_dir/15418hc1_large.html \
	html_dir/15418hc2.html \
	html_dir/15418hc2_large.html \
	html_dir/15418hn1.html \
	html_dir/15418hn1_large.html \
	html_dir/15418hn2.html \
	html_dir/15418hn2_large.html \
	html_dir/15418p1.html \
	html_dir/15418p1_large.html \
	html_dir/15418p2.html \
	html_dir/15418p2_large.html \
	html_dir/15418rrtar5.html \
	html_dir/15418rrtar5_large.html \
	html_dir/15418tar5.html \
	html_dir/15418tar5_large.html \
	html_dir/15418tmp5y.html \
	html_dir/15418tmp5y_large.html \
	html_dir/15418y.html \
	html_dir/15418y_large.html \
	session_dir/15418ac5.ds \
	session_dir/15418acdd \
	session_dir/15418am1.ds \
	session_dir/15418am2.ds \
	session_dir/15418as1.ds \
	session_dir/15418as2.ds \
	session_dir/15418c2.ds \
	session_dir/15418d1.ds \
	session_dir/15418d2.ds \
	session_dir/15418hc1.ds \
	session_dir/15418hc2.ds \
	session_dir/15418hn1.ds \
	session_dir/15418hn2.ds \
	session_dir/15418p1.ds \
	session_dir/15418p2.ds \
	session_dir/15418rrtar5.ds \
	session_dir/15418tar5.ds )

foreach file ($files)
  if (! -f $file) then
    echo "  Output file $file is missing"
    set result = 1
  endif
end


set file = "data_dir/15418d1.dat"
set line = '^1 1 MET 0.085 0.0 -2.931 0.636$'
source tests/check4line
set line = '^1 90 GLY 0.0 0.0 1.355 0.0$'
source tests/check4line

set file = "data_dir/15418tar5.dat"
set line = '^3 8 LEU -97.00 -37.00 3_7_C C 3_8_N N 3_8_CA CA 3_8_C C phi -56.22 0'
source tests/check4line
set line = '^3 33 GLU -80.00 0.00 3_33_N N 3_33_CA CA 3_33_C C 3_34_N N psi -12.12 0'
source tests/check4line
set line = '^4 8 LEU -97.00 -37.00 4_7_C C 4_8_N N 4_8_CA CA 4_8_C C phi -56.44 0'
source tests/check4line
set line = '^4 33 GLU -80.00 0.00 4_33_N N 4_33_CA CA 4_33_C C 4_34_N N psi -18.58 0'
source tests/check4line
set line = '^1 3 SER -100.00 -40.00 1_2_C C 1_3_N N 1_3_CA CA 1_3_C C phi -50.44 1.79'
source tests/check4line
set line = '^1 88 LEU 140.00 -20.00 1_88_N N 1_88_CA CA 1_88_CB CB 1_88_CG CG chi-1 -70.36 72.72'
source tests/check4line
set line = '^2 3 SER -100.00 -40.00 2_2_C C 2_3_N N 2_3_CA CA 2_3_C C phi -53.60 0'
source tests/check4line
set line = '^2 88 LEU 140.00 -20.00 2_88_N N 2_88_CA CA 2_88_CB CB 2_88_CG CG chi-1 -68.89 0'
source tests/check4line

set file = "data_dir/15418rrtar5.dat"
set line = '^3 8 LEU -97.0 -37.0 3_7_C C 3_8_N N 3_8_CA CA 3_8_C C phi 0.0 0.0'
source tests/check4line
set line = '^3 33 GLU -80.0 0.0 3_33_N N 3_33_CA CA 3_33_C C 3_34_N N psi 0.0 0.0'
source tests/check4line
set line = '^4 8 LEU -97.0 -37.0 4_7_C C 4_8_N N 4_8_CA CA 4_8_C C phi 0.0 0.0'
source tests/check4line
set line = '^4 33 GLU -80.0 0.0 4_33_N N 4_33_CA CA 4_33_C C 4_34_N N psi 0.0 0.0'
source tests/check4line
set line = '^1 3 SER -100.0 -40.0 1_2_C C 1_3_N N 1_3_CA CA 1_3_C C phi 0.0 0.0'
source tests/check4line
set line = '^1 88 LEU -220.0 -20.0 1_88_N N 1_88_CA CA 1_88_CB CB 1_88_CG CG chi-1 0.0 0.0'
source tests/check4line
set line = '^2 3 SER -100.0 -40.0 2_2_C C 2_3_N N 2_3_CA CA 2_3_C C phi 0.0 0.0'
source tests/check4line
set line = '^2 88 LEU -220.0 -20.0 2_88_N N 2_88_CA CA 2_88_CB CB 2_88_CG CG chi-1 0.0 0.0'
source tests/check4line


set file = "html_dir/15418y.html"
set line = '<td><a href="http://devise.cs.wisc.edu/cgi-bin/bmrb/make_view?pdbid=2JTT&number=15418&do_tar=3&coord_index=5&size_str=">2JTT</a></td>'
source tests/check4line
set line = '<td><a href="http://devise.cs.wisc.edu/cgi-bin/bmrb/make_view?pdbid=2JTT&number=15418&do_rrtar=3&coord_index=5&size_str=">2JTT</a></td>'
source tests/check4line

set file = "html_dir/15418y_large.html"
set line = '<td><a href="http://devise.cs.wisc.edu/cgi-bin/bmrb/make_view?pdbid=2JTT&number=15418&do_tar=3&coord_index=5&size_str=_large">2JTT</a></td>'
source tests/check4line
set line = '<td><a href="http://devise.cs.wisc.edu/cgi-bin/bmrb/make_view?pdbid=2JTT&number=15418&do_rrtar=3&coord_index=5&size_str=_large">2JTT</a></td>'
source tests/check4line


echo -n "Test_bug090 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
