#! /bin/csh -f

# Test the minimum NMR-STAR file needed to process Pistachio data.

set result = 0

rm -f */simple_pistachio*

# Process the sample Pistachio data.
echo -n "Processing NMR-STAR for Pistachio data: "
./s2d -nomail -file test_data/bmr_simple_pistachio.str.nmrstr -name simple_pistachio -force \
  -check_res_list
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif


echo "Checking output files"

set files = (data_dir/simple_pistachioas1.dat \
	data_dir/simple_pistachiod1.dat \
	data_dir/simple_pistachiohn1.dat \
	data_dir/simple_pistachiomd.dat \
	data_dir/simple_pistachiop1.dat \
	data_dir/simple_pistachiops1.dat \
	data_dir/simple_pistachiopsac1.dat \
	data_dir/simple_pistachiorc1.dat \
	data_dir/simple_pistachiorl1.dat \
	html_dir/simple_pistachioas1.html \
	html_dir/simple_pistachiod1.html \
	html_dir/simple_pistachiohn1.html \
	html_dir/simple_pistachiop1.html \
	html_dir/simple_pistachiops1.html \
	html_dir/simple_pistachioy.html \
	session_dir/simple_pistachioacdd \
	session_dir/simple_pistachioas1.ds \
	session_dir/simple_pistachiod1.ds \
	session_dir/simple_pistachiohn1.ds \
	session_dir/simple_pistachiop1.ds \
	session_dir/simple_pistachiops1.ds)

foreach file ($files)
  if (! -f $file) then
    echo "  Output file $file is missing"
    set result = 1
  endif
end


echo -n "Test30 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
