#! /bin/csh -f

# Tests chem shift reference processing (needs stuff on leech at BMRB
# to work right).

echo -n "Processing NMR-STAR"
./s2d -nomail -bmrbid 4336 -do_csr 1 -force -check_res_list

if ($status != 0) then
  echo "First invocation of s2d failed!"
  exit 1
endif

echo -n "Processing chemical shift reference"
./s2d -nomail -bmrbid 4336 -pdbid 1HTP -coord_index 2 -do_csr 2 -force \
  -check_res_list

if ($status != 0) then
  echo "Second invocation of s2d failed!"
  exit 1
endif
