#! /bin/csh -f

# Hopefully final phase of torsion angle processing -- just process
# by using the PDB ID -- need to send request to the restraint grid
# and parse the result.

set result = 0

rm -r -f */4020*

echo -n "Processing NMR-STAR: "
./s2d -nomail -bmrbid 4020 -force -check_res_list -check_pct
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif
mv tmp/s2d.out tmp/s2d.out1

echo -n "Processing mmCIF and torsion angle restraints: "
./s2d -nomail -bmrbid 4020 -pdbid 1brv -coord_index 1 -force \
  -do_tar 3 -check_res_list -check_pct
if ($status != 0) then
  echo "Second invocation of s2d failed!"
  set result = 1
endif


source tests/test_tar1_check


echo -n "Test_tar1i result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
