#! /bin/csh -f

# Tests visualization of SPARTA-calculated theoretical deltashifts
# (NMR-STAR 3.1 file).

set result = 0

rm -r -f */*/uvd16385*
rm -r -f */.*/uvd16385*

echo -n "Processing NMR-STAR: "
./make_uvd file=test_data/sd16385_3.str\&name=uvd16385\&force=1\&sparta_file=test_data/bmr16385_3_sparta.str
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif

echo "Checking output files"

set files = ( data_dir/uvd/uvd16385am1.dat \
	data_dir/uvd/uvd16385amac1.dat \
	data_dir/uvd/uvd16385as1.dat \
	data_dir/uvd/uvd16385c1.dat \
	data_dir/uvd/uvd16385d1.dat \
	data_dir/uvd/uvd16385hc1.dat \
	data_dir/uvd/uvd16385hn1.dat \
	data_dir/uvd/uvd16385md.dat \
	data_dir/uvd/uvd16385p1.dat \
	data_dir/uvd/uvd16385rc1.dat \
	data_dir/uvd/uvd16385rl.dat \
	data_dir/uvd/uvd16385sd1.dat \
	data_dir/uvd/uvd16385sd1_models.dat \
	html_dir/uvd/uvd16385am1.html \
	html_dir/uvd/uvd16385am1_large.html \
	html_dir/uvd/uvd16385as1.html \
	html_dir/uvd/uvd16385as1_large.html \
	html_dir/uvd/uvd16385c1.html \
	html_dir/uvd/uvd16385c1_large.html \
	html_dir/uvd/uvd16385d1.html \
	html_dir/uvd/uvd16385d1_large.html \
	html_dir/uvd/uvd16385hc1.html \
	html_dir/uvd/uvd16385hc1_large.html \
	html_dir/uvd/uvd16385hn1.html \
	html_dir/uvd/uvd16385hn1_large.html \
	html_dir/uvd/uvd16385p1.html \
	html_dir/uvd/uvd16385p1_large.html \
	html_dir/uvd/uvd16385sd1.html \
	html_dir/uvd/uvd16385sd1_large.html \
	html_dir/uvd/uvd16385y.html \
	html_dir/uvd/uvd16385y_large.html \
	session_dir/.uvd/uvd16385acdd \
	session_dir/.uvd/uvd16385/uvd16385am1.ds \
	session_dir/.uvd/uvd16385/uvd16385as1.ds \
	session_dir/.uvd/uvd16385/uvd16385c1.ds \
	session_dir/.uvd/uvd16385/uvd16385d1.ds \
	session_dir/.uvd/uvd16385/uvd16385hc1.ds \
	session_dir/.uvd/uvd16385/uvd16385hn1.ds \
	session_dir/.uvd/uvd16385/uvd16385p1.ds \
	session_dir/.uvd/uvd16385/uvd16385sd1.ds )

foreach file ($files)
  if (! -f $file) then
    echo "  Output file $file is missing"
    set result = 1
  endif
end


set file = "data_dir/uvd/uvd16385d1.dat"
set line = '^1 1 MET -0.521 0.0 -1.49 0.347$'
source tests/check4line
set line = '^1 108 GLU -0.022 -0.635 -0.569 1.427$'
source tests/check4line

set file = "data_dir/uvd/uvd16385sd1.dat"
set line = '^1 1 2 GLU -0.286 -1.14 0.09 0.731 0.0 0.0$'
source tests/check4line
set line = '^1 1 107 LEU 0.242 -1.544 -1.754 0.886 -0.059 -0.457$'
source tests/check4line
set line = '^1 20 2 GLU -0.143 -1.812 -0.099 0.943 0.0 0.0$'
source tests/check4line
set line = '^1 20 107 LEU -0.08 -0.42 1.02 0.144 1.538 0.054$'
source tests/check4line
set line = '^1 0 2 GLU -0.245 -1.449 0.202 0.053 0.0 0.0$'
source tests/check4line
set line = '^1 0 107 LEU -0.031 0.038 0.022 0.675 0.875 -0.095$'
source tests/check4line

set file = "html_dir/uvd/uvd16385y.html"
set line = '^<p><b>SPARTA-calculated chemical shift deltas</b></p><table border>$'
source tests/check4line
set line = '^    <td><a href="uvd16385sd1.html">106 residues</a></td>$'
source tests/check4line

set file = "html_dir/uvd/uvd16385y_large.html"
set line = '^<p><b>SPARTA-calculated chemical shift deltas</b></p><table border>$'
source tests/check4line
set line = '^    <td><a href="uvd16385sd1_large.html">106 residues</a></td>$'
source tests/check4line

set file = "html_dir/uvd/uvd16385sd1.html"
set line = '^  SPARTA-calculated Chemical Shift Delta (entity assembly 1)$'
source tests/check4line

set file = "data_dir/uvd/uvd16385sd1_models.dat"
set line = '^Avg	0$'
source tests/check4line
set line = '^20	20$'
source tests/check4line


echo -n "Test_sparta3_3mu result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
