#! /bin/csh -f

# Tests visualization of SPARTA-calculated theoretical deltashifts
# (NMR-STAR 3.1 file).

set result = 0

rm -f */16387*

echo -n "Processing NMR-STAR: "
./s2d -file test_data/bmr16387_3.str -name 16387 -force -check_res_list \
  -check_pct -sparta_file test_data/bmr16387_sparta.str_v3
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif

source tests/test_sparta5_check

#TEMP? (until SPARTA output is fixed)
set file = "data_dir/16387sd1.dat"
set line = '^1 0 2 GLU 0.095 0.0 -0.653 0.0 0.0 -0.051$'
source tests/check4line
set line = '^1 20 80 HIS -0.155 0.0 2.095 0.0 0.0 -0.193$'
source tests/check4line


echo -n "Test_sparta5_3 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
