#! /bin/csh -f

# Test bug 105.

set result = 0

rm -r -f */7033*

echo -n "Processing NMR-STAR and mmCIF: "
./s2d -nomail -name 7033 -file test_data/bmr7033_3.str -do_pdb 2 -force -check_pct
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif


echo "Checking output files"

set files = ( data_dir/7033ac1.dat \
	data_dir/7033ac2.dat \
	data_dir/7033am1.dat \
	data_dir/7033am2.dat \
	data_dir/7033amac1.dat \
	data_dir/7033amac2.dat \
	data_dir/7033as1.dat \
	data_dir/7033as2.dat \
	data_dir/7033c1.dat \
	data_dir/7033c2.dat \
	data_dir/7033d1.dat \
	data_dir/7033d2.dat \
	data_dir/7033hc1.dat \
	data_dir/7033hc2.dat \
	data_dir/7033hn1.dat \
	data_dir/7033hn2.dat \
	data_dir/7033md.dat \
	data_dir/7033p1.dat \
	data_dir/7033p2.dat \
	data_dir/7033rc1.dat \
	data_dir/7033rc2.dat \
	data_dir/7033rl.dat \
	html_dir/7033/7033ac1.html \
	html_dir/7033/7033ac1_large.html \
	html_dir/7033/7033ac2.html \
	html_dir/7033/7033ac2_large.html \
	html_dir/7033/7033am1.html \
	html_dir/7033/7033am1_large.html \
	html_dir/7033/7033am2.html \
	html_dir/7033/7033am2_large.html \
	html_dir/7033/7033as1.html \
	html_dir/7033/7033as1_large.html \
	html_dir/7033/7033as2.html \
	html_dir/7033/7033as2_large.html \
	html_dir/7033/7033c1.html \
	html_dir/7033/7033c1_large.html \
	html_dir/7033/7033c2.html \
	html_dir/7033/7033c2_large.html \
	html_dir/7033/7033d1.html \
	html_dir/7033/7033d1_large.html \
	html_dir/7033/7033d2.html \
	html_dir/7033/7033d2_large.html \
	html_dir/7033/7033hc2.html \
	html_dir/7033/7033hc2_large.html \
	html_dir/7033/7033hn2.html \
	html_dir/7033/7033hn2_large.html \
	html_dir/7033/7033p1.html \
	html_dir/7033/7033p1_large.html \
	html_dir/7033/7033p2.html \
	html_dir/7033/7033p2_large.html \
	html_dir/7033/7033y.html \
	html_dir/7033/7033y_large.html \
	session_dir/7033/7033ac1.ds \
	session_dir/7033/7033ac2.ds \
	session_dir/7033/7033acdd \
	session_dir/7033/7033am1.ds \
	session_dir/7033/7033am2.ds \
	session_dir/7033/7033as1.ds \
	session_dir/7033/7033as2.ds \
	session_dir/7033/7033c1.ds \
	session_dir/7033/7033c2.ds \
	session_dir/7033/7033d1.ds \
	session_dir/7033/7033d2.ds \
	session_dir/7033/7033hc2.ds \
	session_dir/7033/7033hn2.ds \
	session_dir/7033/7033p1.ds \
	session_dir/7033/7033p2.ds )

foreach file ($files)
  if (! -f $file) then
    echo "  Output file $file is missing"
    set result = 1
  endif
end


echo -n "Test70 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
