#! /bin/csh -f

# This is testing the "link-only" chem shift reference processing,
# instead of doing it all in one step.

set result = 0

set noleech = 0

if ($#argv > 0) then
  if (xx$1 == xx-noleech) then
    set noleech = 1
  endif
endif

rm -f */4336*

if ($noleech) then
  tests/test23_noleech
  if ($status) then
    set result = 1
  endif
else
  tests/test23_main
  if ($status) then
    set result = 1
  endif
endif

echo "Checking output files"

set files = (data_dir/4336as1.dat \
	data_dir/4336c1.dat \
	data_dir/4336csr2_1.dat \
	data_dir/4336csr2_2.dat \
	data_dir/4336csr2_3.dat \
	data_dir/4336csr2_4.dat \
	data_dir/4336csr2_5.dat \
	data_dir/4336csr2src.dat \
	data_dir/4336d1.dat \
	data_dir/4336hn1.dat \
	data_dir/4336md.dat \
	data_dir/4336p1.dat \
	data_dir/4336rc1.dat \
	data_dir/4336rl1.dat \
	html_dir/4336as1.html \
	html_dir/4336c1.html \
	html_dir/4336csr12.html \
	html_dir/4336csr22.html \
	html_dir/4336csr32.html \
	html_dir/4336d1.html \
	html_dir/4336hn1.html \
	html_dir/4336p1.html \
	html_dir/4336y.html \
	html_dir/4336y_large.html \
	session_dir/4336acdd \
	session_dir/4336as1.ds \
	session_dir/4336c1.ds \
	session_dir/4336csr12.ds \
	session_dir/4336csr22.ds \
	session_dir/4336csr32.ds \
	session_dir/4336d1.ds \
	session_dir/4336hn1.ds \
	session_dir/4336p1.ds \
	data_dir/4336am1.dat \
	html_dir/4336am1.html \
	session_dir/4336am1.ds \
	html_dir/4336am1_large.html \
	html_dir/4336as1_large.html \
	html_dir/4336c1_large.html \
	html_dir/4336csr12_large.html \
	html_dir/4336csr22_large.html \
	html_dir/4336csr32_large.html \
	html_dir/4336d1_large.html \
	html_dir/4336hn1_large.html \
	html_dir/4336p1_large.html \
	html_dir/4336tmp2y_large.html)

foreach file ($files)
  if (! -f $file) then
    echo "  Output file $file is missing"
   set result = 1
  endif
end

# Check for correct chem shift ref links in summary html file.
if (`grep -l 'make_view?pdbid=1DXM&number=4336&do_csr=2&coord_index=1&csr_index=1' html_dir/4336y.html` == "") then
  echo "1DXM chem shift ref 1 link missing"
  set result = 1
endif

if (`grep -l 'make_view?pdbid=1DXM&number=4336&do_csr=2&coord_index=1&csr_index=2' html_dir/4336y.html` == "") then
  echo "1DXM chem shift ref 2 link missing"
  set result = 1
endif

if (`grep -l 'make_view?pdbid=1DXM&number=4336&do_csr=2&coord_index=1&csr_index=3' html_dir/4336y.html` == "") then
  echo "1DXM chem shift ref 3 link missing"
  set result = 1
endif

if (`grep -l 'make_view?pdbid=1HTP&number=4336&do_csr=2&coord_index=2&csr_index=1' html_dir/4336y.html` == "") then
  echo "1HTP chem shift ref 1 link missing"
  set result = 1
endif

if (`grep -l 'make_view?pdbid=1HTP&number=4336&do_csr=2&coord_index=2&csr_index=2' html_dir/4336y.html` == "") then
  echo "1HTP chem shift ref 2 link missing"
  set result = 1
endif

if (`grep -l 'make_view?pdbid=1HTP&number=4336&do_csr=2&coord_index=2&csr_index=3' html_dir/4336y.html` == "") then
  echo "1HTP chem shift ref 3 link missing"
  set result = 1
endif

if (`grep -l 'make_view?pdbid=1HPC&number=4336&do_csr=2&coord_index=3&csr_index=1' html_dir/4336y.html` == "") then
  echo "1HPC chem shift ref 1 link missing"
  set result = 1
endif

if (`grep -l 'make_view?pdbid=1HPC&number=4336&do_csr=2&coord_index=3&csr_index=2' html_dir/4336y.html` == "") then
  echo "1HPC chem shift ref 2 link missing"
  set result = 1
endif

if (`grep -l 'make_view?pdbid=1HPC&number=4336&do_csr=2&coord_index=3&csr_index=3' html_dir/4336y.html` == "") then
  echo "1HPC chem shift ref 3 link missing"
  set result = 1
endif


echo -n "Test23 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
