#! /bin/csh -f

# Pretty much "normal" processing except that we're doing both the BMRB
# file and the PDB file in a single step (both from the web).
# This tests bug 028.
# Note: we're also testing that with do_lacs 1 we don't fail overall
# even when we can't find the LACS file.

set result = 0

rm -r -f */4867*

echo -n "Processing NMR-STAR and mmCIF: "
./s2d -nomail -bmrbid 4867 -do_pdb 2 -force -check_res_list \
  -do_lacs 1 -lacs_url file:test_data/ -check_pct
if ($status != 0) then
  echo "First invocation of s2d failed!"
  set result = 1
endif


source tests/test14_check


echo -n "Test14 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
