#! /bin/csh -f

# Tests "upload and visualize" mode.

#TEMP -- this needs changes to the dummy CSR server to work other
# than with a real ChemShift setup.

set result = 0

rm -f */*/test48_out*
rm -f */.*/test48_out*

echo -n "Processing NMR-STAR: "
./uvd -file test_data/20070314_79717.str -name test48_out -do_csr 2 -force \
  -check_pct
if ($status != 0) then
  echo "First invocation of uvd failed!"
  set result = 1
endif


echo "Checking output files"

set files = ( data_dir/uvd/test48_outam1.dat \
	data_dir/uvd/test48_outamac1.dat \
	data_dir/uvd/test48_outas1.dat \
	data_dir/uvd/test48_outc1.dat \
	data_dir/uvd/test48_outcsr1_1.dat \
	data_dir/uvd/test48_outcsr1_2.dat \
	data_dir/uvd/test48_outcsr1_3.dat \
	data_dir/uvd/test48_outcsr1_4.dat \
	data_dir/uvd/test48_outcsr1_5.dat \
	data_dir/uvd/test48_outcsr1_data.out \
	data_dir/uvd/test48_outcsr1src.dat \
	data_dir/uvd/test48_outd1.dat \
	data_dir/uvd/test48_outhc1.dat \
	data_dir/uvd/test48_outhn1.dat \
	data_dir/uvd/test48_outmd.dat \
	data_dir/uvd/test48_outp1.dat \
	data_dir/uvd/test48_outrc1.dat \
	data_dir/uvd/test48_outrl.dat \
	html_dir/uvd/test48_outam1.html \
	html_dir/uvd/test48_outam1_large.html \
	html_dir/uvd/test48_outas1.html \
	html_dir/uvd/test48_outas1_large.html \
	html_dir/uvd/test48_outc1.html \
	html_dir/uvd/test48_outc1_large.html \
	html_dir/uvd/test48_outcsr11.html \
	html_dir/uvd/test48_outcsr11_large.html \
	html_dir/uvd/test48_outcsr21.html \
	html_dir/uvd/test48_outcsr21_large.html \
	html_dir/uvd/test48_outcsr31.html \
	html_dir/uvd/test48_outcsr31_large.html \
	html_dir/uvd/test48_outd1.html \
	html_dir/uvd/test48_outd1_large.html \
	html_dir/uvd/test48_outhc1.html \
	html_dir/uvd/test48_outhc1_large.html \
	html_dir/uvd/test48_outhn1.html \
	html_dir/uvd/test48_outhn1_large.html \
	html_dir/uvd/test48_outp1.html \
	html_dir/uvd/test48_outp1_large.html \
	html_dir/uvd/test48_outy.html \
	html_dir/uvd/test48_outy_large.html \
	session_dir/.uvd/test48_outacdd \
	session_dir/.uvd/test48_outam1.ds \
	session_dir/.uvd/test48_outas1.ds \
	session_dir/.uvd/test48_outc1.ds \
	session_dir/.uvd/test48_outcsr11.ds \
	session_dir/.uvd/test48_outcsr21.ds \
	session_dir/.uvd/test48_outcsr31.ds \
	session_dir/.uvd/test48_outd1.ds \
	session_dir/.uvd/test48_outhc1.ds \
	session_dir/.uvd/test48_outhn1.ds \
	session_dir/.uvd/test48_outp1.ds )
	
foreach file ($files)
  if (! -f $file) then
    echo "  Output file $file is missing"
    set result = 1
  endif
end


echo -n "Test48 result: "
if ($result == 0) then
  echo "OK"
  exit 0
else
  echo "FAILED"
  exit 1
endif
